import React,{useState,useEffect,useRef} from 'react';
import {action,request} from '../services/api.js';
import Comps from '../features/comps-map/Comps.jsx';
import DealForm from '../features/property-search/DealForm.jsx';
import {Valuation,PropertyDetails,Economics,Scenarios,Sensitivity,Evidence,Questions,Provenance} from '../components/Panels.jsx';
import {humanizeStatus} from '../presentation.js';
import {text} from '../utils/display.js';
export default function App(){
  const [state,setState]=useState('IDLE'),[model,setModel]=useState(null),[session,setSession]=useState(null),[mode,setMode]=useState('property'),[message,setMessage]=useState(''),[pending,setPending]=useState(null),[report,setReport]=useState(null),[reportBusy,setReportBusy]=useState(false),[reportError,setReportError]=useState('');
  const [health,setHealth]=useState(null),[healthError,setHealthError]=useState(''),[refresh,setRefresh]=useState(false);
  const loading=useRef(false),form=useRef(null);
  useEffect(()=>{let active=true;request('health').then(value=>{if(active)setHealth(value);}).catch(e=>{if(active)setHealthError(e.message);});return()=>{active=false;};},[]);
  const busy=['RESOLVING','LOADING_EVIDENCE'].includes(state);
  async function load(endpoint,data,next='LOADING_EVIDENCE'){
    if(loading.current)return;loading.current=true;
    setModel(null);setSession(null);setPending(null);setReport(null);setMessage('');setReportError('');setState(next);
    try{const result=await action(endpoint,data);if(result.model){setModel(result.model);setSession(result.sessionId);setMode(result.model.mode);setState(result.model.state);}else{setState(result.state);setMessage(result.message);setPending(result);}}
    catch(error){setState('ERROR');setMessage(error.message);}finally{loading.current=false;}
  }
  async function generate(){setReportBusy(true);setReportError('');try{setReport(await action('report',{sessionId:session}));}catch(e){setReportError(e.message);}finally{setReportBusy(false);}}
  const p=model?.property;
  const cards=model&&[{label:'Estimated value',value:p?.valuation?.price==null?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(p.valuation.price)},{label:'Provider range',value:p?.valuation?.low!=null&&p?.valuation?.high!=null?`${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(p.valuation.low)} – ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(p.valuation.high)}`:'Not available'},{label:'Comparable properties',value:`${model.comps?.length??0} available`}];
  const propertyNav=<nav className="section-nav" aria-label="Workspace sections"><a href="#overview">Overview</a><a href="#valuation">Valuation</a><a href="#comps">Comps & map</a><a href="#details">Property Details</a><a href="#evidence">Evidence</a><a href="#sources">Sources</a></nav>;
  const dealNav=<nav className="section-nav" aria-label="Workspace sections"><a href="#overview">Overview</a><a href="#valuation">Valuation</a><a href="#comps">Comps & map</a><a href="#details">Property Details</a>{model?.analysis&&<><a href="#economics">Economics</a><a href="#scenarios">Scenarios</a><a href="#sensitivity">Sensitivity</a></>}<a href="#evidence">Evidence</a>{model?.analysis&&<a href="#questions">Questions</a>}<a href="#sources">Sources</a></nav>;
  return <><header className="topbar"><a href="#" className="brand">PROPERTY <span>INTELLIGENCE</span></a><nav aria-label="Main navigation"><a href="#analyze">Analyze Property</a><a href="#fixtures">Saved Fixtures</a></nav><span className="internal">LOCAL / INTERNAL</span></header><main><div className="intro"><p className="eyebrow">INDEPENDENT EVIDENCE · EXPLICIT ASSUMPTIONS</p><h1>Property intelligence workbench</h1><p>What is claimed. What the evidence reports. What the model calculates. What remains unknown.</p></div>
  <section id="analyze" className="search-panel"><form ref={form} onSubmit={e=>{e.preventDefault();if(health?.rentcastConfigured)load('properties/analyze',{address:new FormData(e.target).get('address'),refresh,acknowledgeQuota:refresh},'RESOLVING');}}><label htmlFor="address">Property address</label><div className="search-row"><input id="address" name="address" placeholder="Street, city, state ZIP" required maxLength="300"/><select aria-label="Analysis mode" disabled={busy||reportBusy} value={mode} onChange={e=>{setMode(e.target.value);setModel(null);setState('IDLE');setReport(null);setPending(null);}}><option value="property">Property Mode</option><option value="deal">Deal Mode</option></select><button disabled={busy||reportBusy||!health?.rentcastConfigured}>Analyze Property</button><button type="button" disabled={busy||reportBusy} onClick={()=>load('resolve',{address:new FormData(form.current).get('address'),mode},'RESOLVING')}>Analyze cached evidence</button></div></form><label><input type="checkbox" checked={refresh} disabled={busy||reportBusy||!health?.rentcastConfigured} onChange={e=>setRefresh(e.target.checked)}/> Refresh evidence — may consume RentCast quota and creates new provenance.</label><p className="muted">{health?.rentcastConfigured?'Live analysis is available only through an explicit action. Saved fixtures and cached evidence are preferred.':'Live analysis is disabled: the server provider is unavailable or not configured. Saved fixtures remain usable.'} No provider calls on page load. Sessions and manual deal entries are nonpersistent.</p>{healthError&&<p role="alert">{healthError}</p>}<div id="fixtures" className="fixture-buttons"><span>Saved fixtures</span>{['fantasia','bass','joyce'].map(id=><button key={id} disabled={busy||reportBusy} onClick={()=>load('fixture',{id,mode})}>{id==='fantasia'?'Florida Portfolio / Fantasia':id==='bass'?'Bass — STOP':'Joyce — ambiguous'}</button>)}</div></section>
  <div role="status" aria-live="polite" className={`state state-${state}`} data-testid="state" data-state={state}>{humanizeStatus(state)}{message&&` · ${message}`}</div>
  {pending?.candidates?.length>0&&<section><h2>Confirm intended property</h2>{pending.candidates.map(c=><button disabled={busy||reportBusy} key={c.id} onClick={()=>load('confirm',{confirmationId:pending.confirmationId,id:c.id})}>Confirm {c.address}</button>)}</section>}
  {model&&<><section id="overview" className="property-header"><p className="eyebrow">{model.mode==='deal'?'DEAL MODE':'PROPERTY MODE'} · {humanizeStatus(model.resolutionStatus)}</p><h2>{model.address}</h2><p className="property-subtitle">{p?.propertyType??'Property type not available'} · {text(p?.bedrooms)} BD · {text(p?.bathrooms)} BA · {text(p?.squareFeet)} SF · {p?.yearBuilt==null?'Year built not available':`Built ${p.yearBuilt}`}</p><p className="cache">{model.cache.source??(model.cache.status==='EXISTING_CACHED_EVIDENCE'?'Saved fixture':model.cache.status)} · Retrieved {model.cache.retrievedAt.join(', ')||'Not available'}</p>{['SOURCE_STOP','AMBIGUOUS'].includes(model.state)&&<p className="warning">Identity / representation gate remains unresolved. No independent deal analysis is available. Confirming a saved fixture does not resolve this gate.</p>}<div className="overview-cards">{cards?.map(card=><div className="overview-card" key={card.label}><span>{card.label}</span><strong>{card.value}</strong></div>)}</div>{model.mode==='property'&&state==='READY_PROPERTY'&&<div className="create-deal"><button disabled={busy||reportBusy} onClick={()=>load('deal/start',{sessionId:session})}>Create Deal Analysis</button><span>Add acquisition, repair, resale and holding assumptions to evaluate break-even, scenarios and sensitivity.</span></div>}{model.cache.limitation&&<p className="muted">{model.cache.limitation}</p>}{model.mode==='deal'&&<><p className="warning">{model.warning}</p>{health?.pdfAvailable===false?<p>PDF generation is currently available in the local analyst runtime.</p>:<button onClick={generate} disabled={reportBusy||!health?.pdfAvailable}>{reportBusy?'Generating review…':'Generate Deal Review PDF'}</button>}{report&&<p><a href={report.download}>Download Independent Deal Review PDF</a> · {report.pages} pages · Model {report.digest.slice(0,12)}</p>}{reportError&&<p role="alert">Report failed: {reportError}</p>}</>}{model.mode==='deal'&&['READY_PROPERTY','READY_DEAL'].includes(state)&&<DealForm busy={busy||reportBusy} onSubmit={claims=>load('deal',{sessionId:session,claims})}/>}<p>{model.notes.join(' ')}</p></section>
  {model.mode==='property'?propertyNav:dealNav}<Valuation model={model}/><Comps model={model}/><PropertyDetails model={model}/>{model.analysis&&<><Economics model={model}/><Scenarios model={model}/><Sensitivity model={model}/></>}<Evidence model={model}/>{model.analysis&&<Questions model={model}/>}<Provenance model={model}/></>}
  {!model&&state==='IDLE'&&<section className="empty"><h2>Start with an address or saved fixture</h2><p>Property Mode contains only property evidence. Deal Mode adds explicit sponsor or analyst claims and deterministic calculations.</p></section>}</main><footer>Property Intelligence · Internal evidence review · Not verified resale proceeds · No investment conclusion</footer></>;
}
