import './offline.js';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {CACHE,ZIP,ZIP_HASH,PTS,PTS_HASH,fileHash,json} from './io.js';
const cwd=process.cwd(),execute=args=>execFileSync(process.execPath,args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer:8*1024*1024});
const scriptFiles=(await readdir('scripts/sprint6_2')).filter(f=>f.endsWith('.js'));
for(const f of scriptFiles)execute(['--check',`scripts/sprint6_2/${f}`]);
const artifacts=(await readdir('data/validation')).filter(f=>f.startsWith('sprint6_2-')&&!/performance|qa\.json/.test(f));
const before=Object.fromEntries(await Promise.all(artifacts.map(async f=>[f,await fileHash(`data/validation/${f}`)])));
execute(['scripts/sprint6_2/run.js']);
for(const f of artifacts)if(await fileHash(`data/validation/${f}`)!==before[f])throw new Error('DETERMINISTIC_REPLAY_STOP');
const tap=execute(['--test','scripts/sprint6_2/poc.test.js']);
await writeFile(`${CACHE}/poc-tests.tap`,tap);
const tests=Number(tap.match(/# tests (\d+)/)?.[1]),passed=Number(tap.match(/# pass (\d+)/)?.[1]),failed=Number(tap.match(/# fail (\d+)/)?.[1]);
if(tests!==25||passed!==tests||failed!==0)throw new Error('TEST_GATE_STOP');
execute(['scripts/sprint6_2/report.js']);
const docs=(await readdir('docs')).filter(f=>f.startsWith('SPRINT6_2_')&&f.endsWith('.md'));
const paths=[...scriptFiles.map(f=>`scripts/sprint6_2/${f}`),...docs.map(f=>`docs/${f}`),...(await readdir('data/validation')).filter(f=>f.startsWith('sprint6_2-')).map(f=>`data/validation/${f}`)];
let credentialFindings=0,privateFieldFindings=0;
for(const file of paths){const body=await readFile(file,'utf8');
  if(/postgres(?:ql)?:\/\/[^\s"']+|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|AIza[0-9A-Za-z_-]{30,}|sb_secret_[0-9A-Za-z_-]{10,}|(?:DATABASE_URL|RENTCAST_API_KEY)\s*=\s*[^\s;]+/.test(body))credentialFindings++;
  if(file.startsWith('data/validation')&&/"(?:owner_name|ownerName|ASSE_NAME|IN_CARE_OF|ADDR_BILL[123])"\s*:/.test(body))privateFieldFindings++;
}
if(credentialFindings||privateFieldFindings)throw new Error('OUTPUT_PRIVACY_SECURITY_STOP');
const baseline=JSON.parse(await readFile(`${CACHE}/repository-baseline.json`));
for(const f of baseline.files)if(!f.missing&&await fileHash(f.path)!==f.sha256)throw new Error('PROTECTED_FILE_STOP');
if(await fileHash(ZIP)!==ZIP_HASH||await fileHash(PTS)!==PTS_HASH)throw new Error('FINAL_SOURCE_STOP');
const result={status:'PASS',unitTests:{tests,passed,failed},syntaxChecked:scriptFiles.length,deterministicReplay:{artifacts:artifacts.length,byteIdentical:true,excluded:['performance (observational timings)','qa (verification results)']},protectedFiles:{count:baseline.files.length,unchanged:true},sourceHashes:{zip:ZIP_HASH,pts:PTS_HASH,unchanged:true},credentialScan:{filesScanned:paths.length,findings:credentialFindings,privateValueFieldFindings:privateFieldFindings,scope:'New POC scripts/docs/validation only. No credentials/environment loaded.'},providerCalls:0,networkCalls:0,dbConnections:0,dbWrites:0,migrations:0,deployments:0};
await json('data/validation/sprint6_2-qa.json',result);
execute(['scripts/sprint6_2/report.js']);
console.log(JSON.stringify(result,null,2));
