import React,{useState} from 'react';
import {money,percent,text,human} from '../utils/display.js';
import {additionalDueDiligence,displayValue,evidenceSummary,groupEvidence,humanizeKey,humanizeStatus,latestRecord,missingLabel,propertyFacts} from '../presentation.js';
import {SourceDetail} from '../presentation.jsx';

const dateValue=value=>value?new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}):null;
const evidenceValue=(model,field)=>model.evidence?.find(item=>item.field===field);
const fact=(label,value,field)=> <div className="detail-fact" key={label}><dt>{label}</dt><dd>{displayValue(value,field)}</dd></div>;

export function Valuation({model}){
 const p=model.property,v=p?.valuation,a=model.analysis;
 const low=v?.low,point=v?.price,high=v?.high,markers=[['LOW',low,'range'],['ESTIMATED VALUE',point,'point'],['HIGH',high,'range']].filter(([,value])=>Number.isFinite(value));
 const overlays=a?[['BREAK-EVEN',a.breakEven?.salePrice,'break'],['RESALE',a.base?.grossSale,'resale']].filter(([,value])=>Number.isFinite(value)):[];
 const all=[...markers,...overlays].map(([,n])=>n),min=all.length?Math.min(...all):0,max=all.length?Math.max(...all):1,pad=Math.max(1,(max-min)*.12),domainMin=min-pad,domainMax=max+pad,pos=n=>`${Math.max(0,Math.min(100,(n-domainMin)/(domainMax-domainMin)*100))}%`;
 return <section id="valuation"><div className="section-heading"><div><p className="eyebrow">INDEPENDENT VALUE EVIDENCE</p><h2>Valuation</h2></div><span className="badge warning-badge">{humanizeStatus(model.valuationStatus)}</span></div>
  <p>Independent estimate is evidence, not verified resale proceeds.</p>{model.state==='SOURCE_STOP'&&<p className="warning">Property representation needs verification before an independent value can be used.</p>}
  {Number.isFinite(low)&&Number.isFinite(point)&&Number.isFinite(high)?<div className="range-visual" role="img" aria-label={`Estimated value ${money(point)}. Provider range from ${money(low)} to ${money(high)}. ${overlays.map(([label,value])=>`${humanizeKey(label)} ${money(value)}.`).join(' ')}`}>
   <div className="range-track"><div className="range-band" style={{left:pos(low),right:`${100-Number.parseFloat(pos(high))}%`}}/>{markers.map(([label,value,type])=><div className={`range-marker ${type}`} key={label} style={{left:pos(value)}}><span>{label}</span><b>{money(value)}</b></div>)}{overlays.map(([label,value,type])=><div className={`range-marker overlay ${type}`} key={label} style={{left:pos(value)}}><span>{humanizeKey(label)}</span><b>{money(value)}</b></div>)}</div>
   <div className="range-axis"><span>{money(domainMin)}</span><span>Provider range</span><span>{money(domainMax)}</span></div>
  </div>:<p className="unavailable">Estimated value and provider range are {missingLabel('valuation')}.</p>}
  <div className="valuation-legend"><span>Estimated value</span><span>Provider range</span>{model.mode==='deal'&&<span>Deal assumptions</span>}</div>
  {model.property?.propertyType==='Manufactured'&&<p className="warning compact-warning">Manufactured-home tenure and comparability remain unresolved.</p>}
 </section>;
}
export function PropertyDetails({model}){
 const p=model.property??{},features=evidenceValue(model,'features')?.independentValue??p.features,legal=evidenceValue(model,'legalDescription')?.independentValue??p.legalDescription,zoning=evidenceValue(model,'zoning')?.independentValue??p.zoning;
 const last=latestRecord(p.saleHistory),tax=latestRecord(p.taxes),assessment=latestRecord(p.assessments);
 return <section id="details"><div className="section-heading"><div><p className="eyebrow">FACTUAL PROPERTY RECORD</p><h2>Property Details</h2></div><span className="badge">Existing evidence only</span></div>
  <div className="detail-group"><h3>Property</h3><dl className="details-grid">{propertyFacts(model).map(([label,value,field])=>fact(label,value,field))}</dl></div>
  <div className="detail-group"><h3>Transaction & assessment</h3><dl className="details-grid">{fact('Last sale price',p.saleHistory&&last?.[1]?.price,'lastSalePrice')}{fact('Last sale date',p.saleHistory&&last?.[1]?.date?dateValue(last[1].date):null,'lastSaleDate')}{fact('Latest assessment',assessment?.[1]?.value,'assessments')}{fact('Latest property taxes',tax?.[1]?.total,'taxes')}{fact('Sale history',last?`${last[0]} · ${last[1]?.event??'Sale'}`:null,'saleHistory')}</dl>{(Object.keys(p.saleHistory??{}).length>1||Object.keys(p.taxes??{}).length>1||Object.keys(p.assessments??{}).length>1)&&<details><summary>View dated records</summary><pre>{JSON.stringify({taxes:p.taxes,assessments:p.assessments,saleHistory:p.saleHistory},null,2)}</pre></details>}</div>
  <div className="detail-group"><h3>Land & legal</h3><dl className="details-grid">{fact('Zoning',zoning,'zoning')}{fact('Legal description',legal,'legalDescription')}{fact('Land / ownership structure',evidenceValue(model,'landTenure')?.independentValue,'landTenure')}</dl></div>
  <div className="detail-group"><h3>Features</h3>{features&&typeof features==='object'?<dl className="details-grid">{Object.entries(features).map(([key,value])=>fact(humanizeKey(key),value,key))}</dl>:<p className="unavailable">{missingLabel('features')}</p>}</div>
 </section>;
}
export function Economics({model}){
 const a=model.analysis;if(!a)return null;
 const entries=Object.entries(a.base.includedCosts);
 const groups=[['Upfront / cash invested',entries.filter(([field])=>['acquisition','repairs','acquisitionClosingCosts'].includes(field)||a.costModel.costs.find(c=>c.field===field)?.cashTiming==='UPFRONT')],
   ['Holding',entries.filter(([field])=>['spaceRent'].includes(field)||a.costModel.costs.find(c=>c.field===field)?.cashTiming==='HOLDING')],
   ['Disposition',entries.filter(([field])=>['commission','escrow','dispositionClosingCosts'].includes(field)||a.costModel.costs.find(c=>c.field===field)?.cashTiming==='DISPOSITION')]];
 return <section id="economics"><h2>Modeled deal economics</h2><p className="warning">{model.warning}</p><div className="metrics">{[['Modeled proceeds',money(a.base.modeledProceeds)],['Cash invested',money(a.base.scenarioCashInvested)],['Modeled profit / loss',money(a.base.modeledProfit)],['Cash-on-cash',percent(a.base.cashOnCash)]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong><small>Property Intelligence calculation</small></div>)}</div><div className="cost-groups">{groups.map(([title,costs])=><div key={title}><h3>{title}</h3>{costs.length?<dl>{costs.map(([k,v])=><React.Fragment key={k}><dt>{humanizeKey(k)}</dt><dd>{money(v)}</dd></React.Fragment>)}</dl>:<p className="unavailable">No supplied costs in this category.</p>}</div>)}</div><div className="two-columns"><div><h3>Excluded unknown costs</h3><ul>{a.base.excludedUnknownCosts.map(c=><li key={c.field}>{humanizeKey(c.field)} — <strong>Unknown</strong></li>)}</ul></div></div><p>Rent coverage: {a.base.modeledHoldingDays} days. Stated timeline: {a.base.sponsorTimelineDays} days. Cash invested follows explicit known-cost conventions.</p><details><summary>View calculation inputs</summary>{a.costModel.warnings.map(w=><p key={w}>{w}</p>)}<pre>{JSON.stringify(model.claims,null,2)}</pre></details></section>;
}
export function Scenarios({model}){const [all,setAll]=useState(false),a=model.analysis;if(!a)return null;const rows=all?a.scenarios:a.defaultScenarios.map(id=>a.scenarios.find(s=>s.id===id)).filter(Boolean);return <section id="scenarios"><div className="section-heading"><h2>Deterministic scenarios</h2><button onClick={()=>setAll(!all)}>{all?'Show default scenarios':`View all ${a.scenarios.length} scenarios`}</button></div><p>{model.warning} No likelihood is assigned to any case.</p><div className="table-scroll" tabIndex="0"><table><thead><tr><th>Case</th><th>Sale</th><th>Repairs</th><th>Profit / loss</th><th>Cash invested</th><th>CoC</th><th>Change vs base</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.label}<small>{humanizeStatus(s.saleAssumptionEvidenceStatus)}</small></td><td>{money(s.outputs.grossSale)}</td><td>{money(s.outputs.includedCosts?.repairs)}</td><td>{money(s.outputs.modeledProfit)}</td><td>{money(s.outputs.scenarioCashInvested)}</td><td>{percent(s.outputs.cashOnCash)}</td><td>{money(s.outputs.changeVsSponsorDollars)}</td></tr>)}</tbody></table></div></section>;}
export function Sensitivity({model}){const a=model.analysis;if(!a)return null;const unavailable=a.sensitivity.ranking.unavailable??[];return <section id="sensitivity"><h2>Sensitivity & break-even</h2><p>Based only on currently modeled known costs. Modeled break-even: <strong>{money(a.breakEven.salePrice)}</strong>.</p><div className="table-scroll" tabIndex="0"><table><thead><tr><th>Sale assumption</th><th>Maximum acquisition</th><th>Maximum repair budget</th></tr></thead><tbody>{a.breakEven.capacities.map(c=><tr key={c.id}><td>{human(c.id)} · {money(c.saleAssumption)}</td><td>{money(c.maximumAcquisitionPrice)}</td><td>{money(c.maximumRepairBudget)}</td></tr>)}</tbody></table></div><h3>{a.sensitivity.ranking.label}</h3><p>{a.sensitivity.ranking.basis}</p><ol>{a.sensitivity.ranking.rows.map(r=><li key={r.label}>Rank {r.rank} · {humanizeKey(r.label)}: {money(r.modeledProfitChange)} profit change {r.outputs?.status==='PARTIAL'&&<span className="badge">Partial</span>}</li>)}</ol>{unavailable.length>0&&<div className="unavailable-sensitivity"><h3>Sensitivity not currently measurable</h3><ul>{unavailable.map(row=><li key={row.label}>{humanizeKey(row.label)} — <strong>Unavailable</strong><span>Reason: Recurring holding costs not supplied</span></li>)}</ul></div>}<h3>Sale price × repair cost — modeled profit / loss</h3><div className="table-scroll" tabIndex="0"><table><thead><tr><th>Sale case</th>{a.sensitivity.matrix[0].cells.map(c=><th key={c.repairChangePercent}>Repairs +{c.repairChangePercent}%</th>)}</tr></thead><tbody>{a.sensitivity.matrix.map(r=><tr key={r.label}><td>{human(r.label)}</td>{r.cells.map(c=><td key={c.repairChangePercent}>{money(c.modeledProfit)}</td>)}</tr>)}</tbody></table></div></section>;}
function DetailedEvidence({model}){const fields=model.evidence??[],groups=groupEvidence(fields.filter(f=>!/^comps\[\d+\]/.test(f.field))),compCount=model.comps?.length??0;if(compCount)groups.find(g=>g.id==='valuation')?.items.push({field:'comparables',status:'SUPPORTED',supportLevel:'INDEPENDENT_ONLY',independentValue:`${compCount} comparable properties available`,notes:['Provider-listed prices and inactive status do not establish closed sales.']});return <div className="evidence-groups">{groups.map(group=><div className="evidence-group" key={group.id}><h3>{group.title}</h3>{group.items.map((item,index)=><details key={`${item.field}-${index}`}><summary>{humanizeKey(item.field)} <span className={`badge status-${String(item.status).toLowerCase()}`}>{humanizeStatus(item.status)}</span></summary><p>{item.independentValue!==undefined?<>Independent evidence: <strong>{displayValue(item.independentValue,item.field)}</strong></>:item.sponsorValue!==undefined?<>Supplied value: <strong>{displayValue(item.sponsorValue,item.field)}</strong></>:null}</p>{(item.notes??[]).map((note,i)=><p className="detail-note" key={i}>{note}</p>)}{item.field!=='comparables'&&<SourceDetail item={item}/>}</details>)}</div>)}</div>;}
export function Evidence({model}){const deal=Boolean(model.analysis),summary=evidenceSummary(model),due=additionalDueDiligence(model);return <section id="evidence"><h2>{deal?'Evidence Summary & Due Diligence':'Evidence & due diligence'}</h2><p className="caution-copy">Available evidence may come from independent data providers, sponsor inputs, or Property Intelligence calculations. Review source details before treating any item as verified.</p>{deal&&<><div className="evidence-summary" aria-label="Evidence summary">{summary.map(item=><div className="summary-row" key={item.id}><span>{item.label}</span><strong>{item.detail??item.status}</strong></div>)}</div><div className="additional-diligence"><h3>Additional Due Diligence Required</h3>{due.length?<ul>{due.map(item=><li key={item.id}><a href="#questions">{item.question}</a><small>{item.category} · {humanizeStatus(item.status)}</small></li>)}</ul>:<p>No additional material diligence questions are currently generated.</p>}</div><details className="detailed-evidence"><summary>View detailed evidence</summary><p>Field values, machine statuses, dates and provenance remain unchanged below.</p><DetailedEvidence model={model}/></details></>}{!deal&&<DetailedEvidence model={model}/>}</section>;}
export function Questions({model}){const groups=[...new Set(model.questions.map(q=>q.category??q.group))];return <section id="questions"><h2>{model.questionHeading??(model.claimOrigin==='SPONSOR_SUPPLIED'?'Questions for Sponsor':'Due Diligence Questions')}</h2><p>Draft only — not sent.</p>{groups.map(group=><div key={group}><h3>{group}</h3><ul>{model.questions.filter(q=>(q.category??q.group)===group).map(q=><li key={q.id}>{q.question} <small>{humanizeStatus(q.status)}</small></li>)}</ul></div>)}</section>;}
export function Provenance({model}){return <section id="sources"><h2>Sources & provenance</h2><p>Evidence availability is not verification. Calculations use explicitly modeled known costs; no probabilities, investment conclusions or inferred tenure are added.</p><details><summary>View source details and retrieval dates</summary><div className="source-list">{model.provenance.map((p,i)=><p key={i}><strong>{p.source} · {humanizeKey(p.field??'Input reference')}</strong><br/>{p.retrievedAt?dateValue(p.retrievedAt):'Date not supplied'} · {p.status?humanizeStatus(p.status):'Source reference'}<br/>{p.reference??p.rawResponseRef??'Reference not supplied'}</p>)}</div></details><details><summary>View model fingerprint</summary><p><code>{model.digest}</code></p></details></section>;}
