import React,{useEffect,useMemo,useState} from 'react';
import {action} from '../../services/api.js';
import InvestmentReport from './InvestmentReport.jsx';

const money=value=>value==null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);

export default function AcquisitionWorkspace(props){return <><AcquisitionDecision {...props}/><InvestmentReport propertyId={props.propertyId}/></>;}
function AcquisitionDecision({model,propertyId,evidenceSnapshotId,analysisContext}){
  const valuation=model?.property?.valuation??{};
  const [hurdleType,setHurdleType]=useState('CASH_ON_CASH'),[hurdleRate,setHurdleRate]=useState('20'),[exit,setExit]=useState(String(valuation.price??'')),[rehab,setRehab]=useState('0'),[ask,setAsk]=useState(''),[decision,setDecision]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const input=useMemo(()=>({strategy:'FIX_AND_FLIP',hurdle:{type:hurdleType,rate:Number(hurdleRate)/100},selectedExitBasis:'ANALYST_EXIT',exitBases:[{basis:'ANALYST_EXIT',value:Number(exit),evidenceSnapshotId,evidenceStatus:'ANALYST_ENTERED',provenance:[{source:'ANALYST_ENTERED',reference:'Acquisition Decision form'}]}],evidenceSnapshotId,acquisitionCosts:[],dispositionCosts:[],rehab:{items:Number(rehab)>0?[{category:'OTHER',conditionStatus:'UNKNOWN',estimatedCost:Number(rehab),source:'ANALYST_ENTERED'}]:[],noRehabAssumption:Number(rehab)===0},holdingCosts:[],financing:{mode:'CASH'},sellerAskingPrice:ask===''?null:Number(ask)}),[hurdleType,hurdleRate,exit,rehab,ask,evidenceSnapshotId]);
  useEffect(()=>{setDecision(null);},[input,analysisContext]);
  async function calculate(){setBusy(true);setMessage('');try{const result=await action('acquisition-decisions/calculate',{input,...(analysisContext??{})});setDecision(result.decision);if(!analysisContext)setMessage('Save Deal to establish its immutable Analysis Snapshot before saving a decision.');}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  async function save(){if(!propertyId||!evidenceSnapshotId||!decision?.analysisLink)return;setBusy(true);try{const result=await action(`properties/${propertyId}/acquisition-decisions`,{...analysisContext,input,decision,requestKey:globalThis.crypto?.randomUUID?.()});setMessage(`Saved decision ${result.decisionId} · Analysis ${result.analysisSnapshotId}`);}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  return <section id="acquisition-decision" className="acquisition-decision"><p className="eyebrow">ACQUISITION DECISION · FIX & FLIP</p><h2>Maximum Allowable Offer</h2><p className="muted">Deterministic acquisition math only. This is not an investment recommendation.</p><div className="decision-grid"><label>Required return<select value={hurdleType} onChange={event=>setHurdleType(event.target.value)}><option value="CASH_ON_CASH">Cash-on-cash</option><option value="RETURN_ON_TOTAL_PROJECT_COST">Return on total project cost</option><option value="PROFIT_MARGIN_ON_SALE">Profit margin on sale</option></select></label><label>Hurdle %<input type="number" min="0.01" max="99.99" step="0.01" value={hurdleRate} onChange={event=>setHurdleRate(event.target.value)}/></label><label>Analyst exit<input type="number" min="0" step="1" value={exit} onChange={event=>setExit(event.target.value)}/></label><label>Base rehab<input type="number" min="0" step="1" value={rehab} onChange={event=>setRehab(event.target.value)}/></label><label>Seller ask (optional)<input type="number" min="0" step="1" value={ask} onChange={event=>setAsk(event.target.value)}/></label></div><div className="button-row"><button onClick={calculate} disabled={busy||!exit}>{busy?'Calculating…':'Calculate MAO'}</button><button onClick={save} disabled={busy||!decision?.analysisLink||!propertyId||!evidenceSnapshotId}>Save Decision</button></div>{analysisContext&&<p className="muted">Deal economics snapshot: {analysisContext.analysisSnapshotId}</p>}{message&&<p role="status">{message}</p>}{decision&&<div className="decision-results"><h3>Acquisition Decision — Fix & Flip</h3><p>Selected hurdle: <strong>{decision.hurdle.ratePercent.toFixed(1)}% {decision.hurdle.type.replaceAll('_',' ')}</strong></p><div className="overview-cards"><div className="overview-card"><span>Selected MAO</span><strong>{money(decision.calculatedMao)}</strong></div><div className="overview-card"><span>Walk-away price</span><strong>{money(decision.effectiveWalkawayPrice)}</strong></div><div className="overview-card"><span>Target offer</span><strong>{money(decision.targetOffer)}</strong></div><div className="overview-card"><span>Seller ask</span><strong>{money(decision.sellerAskingPrice)}</strong></div></div><p className="status">Completeness: {decision.costCompleteness}</p>{decision.warnings?.length>0&&<ul className="warning">{decision.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul>}<h3>Exit MAOs</h3><table><thead><tr><th>Exit basis</th><th>Value</th><th>MAO</th><th>Evidence</th></tr></thead><tbody>{decision.exitResults.map(result=><tr key={result.exitBasis}><td>{result.exitBasis}</td><td>{money(result.exitValue)}</td><td>{money(result.calculatedMao)}</td><td>{result.exitConflict?'Conflict':result.exitEvidenceStatus}</td></tr>)}</tbody></table><p className="muted">Sensitivity includes Base, +20% and +50% rehab cases without probability language.</p></div>}</section>;
}
