import {money,percent} from '../workbench/model.js';
export const escape=v=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const human=s=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');
const value=v=>escape(v==null?'Unknown':typeof v==='object'?JSON.stringify(v):v);
const table=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const section=(n,title,body)=>`<section><p class="eyebrow">INDEPENDENT DEAL REVIEW / ${n}</p><h1>${escape(title)}</h1>${body}</section>`;
const para=s=>`<p>${escape(s)}</p>`;
function scenarioTable(m){const a=m.analysis;if(!a)return '<p class="warning">Independent deal analysis unavailable while identity / representation remains unresolved. No return estimate supplied.</p>';return table(['Case / basis','Sale','Repairs','Profit / loss','Cash invested','CoC','Δ vs base'],a.defaultScenarios.map(id=>a.scenarios.find(s=>s.id===id)).filter(Boolean).map(s=>[`${escape(s.label)}<small>${escape(s.saleAssumptionEvidenceStatus)}</small>`,money(s.outputs.grossSale),money(s.outputs.includedCosts?.repairs),`<b>${money(s.outputs.modeledProfit)}</b>`,money(s.outputs.scenarioCashInvested),percent(s.outputs.cashOnCash),money(s.outputs.changeVsSponsorDollars)]));}
export function reportHtml(m){
  const a=m.analysis,p=m.property,v=p?.valuation;
  const warning=`<p class="warning">${escape(m.warning)}</p>`;
  const provenance=`<p class="note">Sponsor / entered inputs: ${escape(m.claimOrigin)}. Provider evidence: RentCast / INDEPENDENT_ONLY, retrieved ${escape(m.cache.retrievedAt.join(', ')||'Not available')}. Calculations: Property Intelligence / DERIVED from referenced known costs.</p>`;
  const scale=m.scale.map(s=>`<div class="scale-row"><span>${escape(s.label)}</span><div class="track"><i style="width:${s.position}%"></i></div><b>${escape(s.display)}</b></div>`).join('');
  let html=section('01','Executive deal summary',`<div class="masthead">PROPERTY INTELLIGENCE<br/><span>Independent Deal Review</span></div><h2>${escape(m.address)}</h2><p class="status">${escape(m.resolutionStatus)} · ${escape(m.valuationStatus)}</p>${table(['Metric','Value','Source / status'],m.metrics.map(x=>[escape(x.label),`<b>${escape(x.display)}</b>`,`${escape(x.source)}<small>${escape(x.status)}</small>`]))}${a?table(['Scenario basis','Modeled profit / loss','Cash-on-cash'],['SPONSOR_CASE','INDEPENDENT_AVM_POINT','INDEPENDENT_AVM_HIGH'].map(id=>a.scenarios.find(s=>s.id===id)).filter(Boolean).map(s=>[escape(s.label),`<b>${money(s.outputs.modeledProfit)}</b>`,percent(s.outputs.cashOnCash)])):''}${warning}${para('This review separates supplied claims, independent provider evidence and deterministic calculations. It does not resolve ownership, title, condition, tenure or actual resale proceeds.')}${provenance}`);
  html+=section('02','Property intelligence',`<h2>${escape(m.address)}</h2>${table(['Property field','Provider-reported evidence'],[['Type',value(p?.propertyType)],['Bedrooms / bathrooms',`${value(p?.bedrooms)} / ${value(p?.bathrooms)}`],['Area / year built',`${value(p?.squareFeet)} SF / ${value(p?.yearBuilt)}`],['County',value(p?.county)],['Parcel identifier',value(p?.identifiers?.apn)],['Lot size',`${value(p?.lotSize)} SF`],['Coordinates',value(p?.coordinates)],['Land tenure / park', 'Unknown — not inferred from tax parcel or property type']])}<h2>Identity and location limitations</h2>${m.notes.map(para).join('')}${para('Map omitted: no authorized static-map infrastructure established for this release. Provider coordinates and retained comparable addresses are supplied instead; the interactive coordinate map is not screenshotted.')}${provenance}`);
  html+=section('03','Comparable evidence',`<p>${m.comps.length} retained comps; ${m.comps.filter(c=>c.mappable).length} with provider coordinates. No default filtering or favorable-comp selection.</p><p class="warning">Provider-listed prices are not established closed sales. Inactive does not establish a sale. Land tenure is unknown for every comp.</p>${table(['# / address','Provider-listed price / status','Structure','Context / source'],m.comps.map(c=>[`${c.number}. ${escape(c.address)}<small>${escape(c.propertyType??'Type unknown')} · ${escape(c.tenure)}</small>`,`<b>${escape(c.priceText)}</b><small>${escape(c.badge)}</small>`,`${value(c.bedrooms)} BD / ${value(c.bathrooms)} BA<br/>${value(c.squareFeet)} SF<br/>Built ${value(c.yearBuilt)}`,`${value(c.distance)} mi · ${value(c.daysOnMarket)} DOM<br/>Correlation ${value(c.correlation)}<br/>Lot ${value(c.lotSize)} SF · Unit ${value(c.unit)}<small>RentCast / INDEPENDENT_ONLY<br/>${escape(c.locationStatus)}</small>`]))}${!m.comps.length?para('No independent comparable evidence available for this unresolved property.'):''}${provenance}`);
  html+=section('04','Valuation analysis',`<p class="status">${escape(m.valuationStatus)}</p>${scale||para('Independent valuation unavailable.')}${m.divergence?para(`Entered resale minus AVM point: ${money(m.divergence.vsPoint)}. Entered resale minus AVM high: ${money(m.divergence.vsHigh)}.`):''}<h2>Interpretation boundaries</h2>${m.limitations.map(para).join('')}${para('The scale is deterministic and does not imply a probability distribution. Provider range endpoints are not guaranteed sale outcomes. Sponsor resale remains a supplied projection.')}${provenance}`);
  html+=section('05','Deal economics',`${warning}${a?table(['Modeled item','Amount / result'],[...Object.entries(a.base.includedCosts).map(([k,n])=>[escape(human(k)),money(n)]),['Modeled proceeds',money(a.base.modeledProceeds)],['Cash invested',money(a.base.scenarioCashInvested)],['Modeled profit / loss',`<b>${money(a.base.modeledProfit)}</b>`],['Cash-on-cash',percent(a.base.cashOnCash)],['Fully burdened profit','Unknown — unavailable']]):para('Independent modeled economics withheld due to unresolved identity / representation. Original sponsor claims are not verified.')}${a?`<h2>Unknown costs excluded from the model</h2><p>${a.base.excludedUnknownCosts.map(c=>`${escape(human(c.field))}: <b>Unknown</b>`).join('; ')}.</p>${para(`Rent coverage ${a.base.modeledHoldingDays} days; stated timeline ${a.base.sponsorTimelineDays} days. Cash invested includes acquisition, repairs, rent and explicit upfront additional costs. Commission, escrow and explicit disposition costs are deducted at exit.`)}`:''}${provenance}`);
  html+=section('06','Scenario analysis',`${warning}${scenarioTable(m)}${para('Scenarios are deterministic assumption changes, not forecasts or assigned likelihoods. Negative currency denotes a modeled loss. All unknown costs remain excluded.')}${a?para(`${a.scenarios.length} cases are available in the workbench. This report displays the five specified review cases. Holding scenarios replace rent using explicit 30-day months; they do not model other unknown recurring costs.`):''}${provenance}`);
  html+=section('07','Sensitivity & break-even',`${para('Based only on currently modeled known costs.')}${a?`<h2>Modeled break-even ${money(a.breakEven.salePrice)}</h2>${table(['Sale case','Max acquisition','Max repairs'],a.breakEven.capacities.map(c=>[escape(human(c.id)),money(c.maximumAcquisitionPrice),money(c.maximumRepairBudget)]))}<h2>Deterministic sensitivity ranking</h2>${table(['Rank / perturbation','Profit change'],a.sensitivity.ranking.rows.map(r=>[`${r.rank}. ${escape(r.label)}`,money(r.modeledProfitChange)]))}<h2>Sale × repairs: modeled profit / loss</h2>${table(['Sale case',...a.sensitivity.matrix[0].cells.map(c=>`Repairs +${c.repairChangePercent}%`)],a.sensitivity.matrix.map(r=>[escape(human(r.label)),...r.cells.map(c=>money(c.modeledProfit))]))}${para('Unequal perturbations are ranked by absolute dollar impact; ties share rank. Negative capacity means the assumed sale cannot cover the other currently modeled costs even before that cost category.')}`:para('Thresholds and sensitivity unavailable until independent identity / representation gates are resolved.')}`);
  const supported=m.evidence.filter(f=>f.status==='SUPPORTED'),partial=m.evidence.filter(f=>['PARTIAL','PARTIALLY_SUPPORTED'].includes(f.status)),conflicts=m.evidence.filter(f=>f.status==='CONFLICTING'),missing=m.evidence.filter(f=>!['SUPPORTED','PARTIAL','PARTIALLY_SUPPORTED','CONFLICTING'].includes(f.status));
  html+=section('08','Evidence & due diligence',`<p>Evidence availability is not verified truth. Original fixture assessments remain distinct from any later manual claims. Unknown is never modeled as zero.</p><h2>Supported / available</h2>${table(['Field','Independent evidence'],supported.map(f=>[escape(human(f.field)),value(f.independentValue)]))}<h2>Conflicting</h2>${conflicts.length?table(['Field','Supplied claim','Independent evidence'],conflicts.map(f=>[escape(human(f.field)),value(f.sponsorValue),value(f.independentValue)])):para('No resolved conflict assessment available.')}<h2>Partial evidence — not verified</h2><p>${partial.map(f=>escape(human(f.field))).join('; ')||'No partial assessments supplied'}.</p><p>Supplied amounts do not independently establish costs; provider AVM and listing comps do not establish realized resale. See comparable and valuation sections for retained evidence.</p><h2>Missing / unresolved</h2><p>${missing.map(f=>`${escape(human(f.field))} (${escape(f.status)})`).join('; ')||'No missing-field assessments supplied'}.</p><p class="note">Full field-level claim values, independent values, dates, notes and source references remain available in the workbench and the report's companion model JSON. This page summarizes all assessed fields without reproducing raw comparable payloads.</p>${provenance}`);
  html+=section('09','Questions for sponsor',`<p class="status">DRAFT — NOT SENT</p>${[...new Set(m.questions.map(q=>q.group))].map(group=>`<h2>${escape(group)}</h2><ul>${m.questions.filter(q=>q.group===group).map(q=>`<li>${escape(q.question)} <small>${escape(q.status)}</small></li>`).join('')}</ul>`).join('')}${m.questions.length?'':para('No structured sponsor questions supplied. Resolve missing property identity and evidence before further analysis.')}`);
  const refs=[...new Set(m.provenance.map(p=>p.reference).filter(Boolean))];
  html+=section('10','Sources & methodology',`${provenance}<h2>Input references</h2><ul>${refs.map(r=>`<li class="reference">${escape(r)}</li>`).join('')}</ul><h2>Methodology</h2>${para('Shared normalized view model feeds both the workbench and this report. Existing deterministic underwriting calculates known modeled costs, proceeds, profit, cash-on-cash, break-even and sensitivity. No client-side or report-specific financial engine is used.')}${para('Sponsor package inputs were transcribed into the preserved deal artifact; original source-package date is not supplied. RentCast records are independent provider evidence, not verified truth. Address confirmation establishes intended identity only.')}${para('Material unknown costs are displayed explicitly and excluded from modeled totals. Land tenure, title, restrictions, condition and actual sale outcomes remain unresolved. No simulation, probability model or AI underwriting narrative is used.')}${warning}<p class="reference">Model fingerprint: ${escape(m.digest)}</p><p class="note">Local/internal review. Generated from a frozen server-side model; saved reports are not overwritten.</p>`);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>PROPERTY INTELLIGENCE — Independent Deal Review</title><style>
  @page{size:Letter;margin:0.65in 0.55in 0.65in}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#223d37;font-size:10px;line-height:1.42;margin:0}section{break-before:${a?'page':'auto'};margin-top:${a?'0':'24px'}}section:first-child{break-before:auto}h1{break-after:avoid;font-size:25px;line-height:1.18;margin:5px 0 21px;letter-spacing:-.4px}h2{font-size:14px;margin:21px 0 9px;break-after:avoid}p{margin:10px 0;orphans:3;widows:3;overflow-wrap:anywhere}li{margin:8px 0;break-inside:avoid;overflow-wrap:anywhere}ul{padding-left:18px}.eyebrow{break-after:avoid;font-size:9px;letter-spacing:1px;color:#557567;margin:0}.masthead{font-size:24px;font-weight:bold;padding:20px 0;border-top:3px solid #326b5a;border-bottom:1px solid #bed0c3;line-height:1.4;letter-spacing:1px}.masthead span{font-size:16px;font-weight:normal;letter-spacing:0}.status{font-weight:bold;color:#86561e}.warning{background:#fff2de;border-left:3px solid #a96d29;padding:11px;font-size:10px;font-weight:bold;break-inside:avoid}.note,small{font-size:9px;color:#4a635a}small{display:block;line-height:1.38;margin-top:4px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9.5px;margin:10px 0 18px}thead{display:table-header-group}tr{break-inside:avoid}td,th{text-align:left;padding:8px 7px;border-bottom:1px solid #d2dfd5;vertical-align:top;overflow-wrap:anywhere;word-break:normal}th{background:#eaf1eb;font-size:9px;color:#294d40}th:first-child{width:27%}.scale-row{display:flex;align-items:center;gap:12px;margin:22px 0;font-size:11px;break-inside:avoid}.scale-row span{width:130px}.track{flex:1;background:#e3ece5;height:12px}.track i{display:block;height:12px;background:#3f8067}.scale-row b{width:72px;text-align:right}.scale-row:last-child i{background:#a76f32}.reference{font-size:9px;overflow-wrap:anywhere}.signature{border-top:1px solid #ccc}
  </style></head><body>${html}</body></html>`;
}
