// Gate 12 only. Migration commands and the county import are intentionally unreachable.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createDatabase} from '../../src/persistence/db.js';
import {migrationInputs,digest} from './certification.js';
import {existingFingerprint,enrichmentTables} from './production-certification.js';
import {rollbackOnlyPersistenceQa} from './production-qa.js';
const reportPath='data/validation/sprint6_3-gate12-qa.json';
const result={status:'STOP',gate:12,mode:'ROLLBACK_ONLY',migrationInvocations:0,providerCalls:0,productionCountyImport:false,applicationDeployment:false,databaseQueryCalls:0};let db,client,inTransaction=false,stage='RECEIPTS';
const query=async(sql,values=[])=>{result.databaseQueryCalls++;return client.query(sql,values);};
try{
  const migrationReport=JSON.parse(await readFile('data/validation/sprint6_3-production-schema-certification.json'));assert.equal(migrationReport.migrationApplied,true);assert.equal(migrationReport.migrationInvocations,1);assert.equal(migrationReport.stage,'ROLLBACK_ONLY_SYNTHETIC_PERSISTENCE_QA');
  const diagnostics=JSON.parse(await readFile('data/validation/sprint6_3-production-stop-diagnostics.json'));assert.equal(diagnostics.diagnosticsPassed,true);assert.deepEqual(diagnostics.newTableCounts,{batches:0,observations:0});
  const cert=JSON.parse(await readFile('data/validation/sprint6_3-isolated-schema-certification.json'));assert.equal(cert.status,'PASS');const migrations=await migrationInputs();assert.deepEqual(migrations.map(({filename,checksum})=>({filename,checksum})),cert.migrations);
  process.loadEnvFile('.env');db=createDatabase();client=await db.getPool().connect();assert.equal(client.connection.stream.encrypted,true);assert.equal(client.connection.stream.authorized,true);
  stage='PRE_WRITE_GATES';await query('BEGIN READ ONLY');inTransaction=true;await query("SET LOCAL statement_timeout='60000'");await query("SELECT set_config('search_path', 'public,pg_catalog', true)");
  result.preWriteNamespace=(await query('SELECT current_schema() AS namespace,current_schemas(false) AS namespaces,current_setting(\'search_path\') AS search_path')).rows[0];assert.equal(result.preWriteNamespace.namespace,'public');assert.ok(result.preWriteNamespace.namespaces.includes('public'));assert.equal(result.preWriteNamespace.search_path.replaceAll(' ',''),'public,pg_catalog');
  result.ledgerBefore=(await query('SELECT filename,checksum,applied_at FROM public.property_intelligence_schema_migrations ORDER BY filename')).rows;assert.deepEqual(result.ledgerBefore.map(({filename,checksum})=>({filename,checksum})),cert.migrations);
  const tableInfo=(await query("SELECT tablename,rowsecurity FROM pg_tables WHERE schemaname='public' AND tablename=ANY($1::text[]) ORDER BY tablename",[enrichmentTables])).rows;assert.deepEqual(tableInfo.map(r=>r.tablename),enrichmentTables);assert.ok(tableInfo.every(r=>r.rowsecurity));result.tables=tableInfo;
  result.preWriteCounts=(await query('SELECT (SELECT count(*)::int FROM public.opportunity_assessor_import_batches) AS batches,(SELECT count(*)::int FROM public.opportunity_assessor_enrichments) AS observations')).rows[0];assert.deepEqual(result.preWriteCounts,{batches:0,observations:0});
  result.existingBefore=await existingFingerprint(query,migrationReport.existingTables);assert.deepEqual(result.existingBefore,migrationReport.existingAfterMigration);await query('ROLLBACK');inTransaction=false;
  stage='ROLLBACK_ONLY_SYNTHETIC_QA';await query('BEGIN');inTransaction=true;await query("SELECT set_config('search_path', 'public,pg_catalog', true)");const qaNamespace=(await query('SELECT current_schema() AS namespace,current_schemas(false) AS namespaces')).rows[0];assert.equal(qaNamespace.namespace,'public');assert.ok(qaNamespace.namespaces.includes('public'));result.qaNamespace=qaNamespace;
  try{result.persistenceQa=await rollbackOnlyPersistenceQa(query);}catch(e){result.qaErrorName=e.name;result.qaErrorCode=/^[0-9A-Z]{5}$/.test(e.code??'')?e.code:null;result.qaErrorConstraint=/^[a-z0-9_]+$/.test(e.constraint??'')?e.constraint:null;result.qaErrorMessage=e.name==='AssertionError'&&String(e.message).length<300?e.message:/^[A-Z0-9_]+$/.test(e.message??'')?e.message:'SANITIZED_QA_ERROR';throw e;}assert.equal(result.persistenceQa.committed,false);assert.equal(result.persistenceQa.providerCalls,0);
  await query('ROLLBACK');inTransaction=false;result.persistenceQa.rollbackComplete=true;
  await query('BEGIN READ ONLY');inTransaction=true;await query("SELECT set_config('search_path', 'public,pg_catalog', true)");result.postRollbackCounts=(await query('SELECT (SELECT count(*)::int FROM public.opportunity_assessor_import_batches) AS batches,(SELECT count(*)::int FROM public.opportunity_assessor_enrichments) AS observations')).rows[0];assert.deepEqual(result.postRollbackCounts,{batches:0,observations:0});result.syntheticRows=(await query(`SELECT (SELECT count(*)::int FROM public.opportunity_candidates WHERE candidate_key LIKE $1) AS candidates,(SELECT count(*)::int FROM public.discovery_records r JOIN public.discovery_sources s ON s.id=r.discovery_source_id WHERE s.source_name=$2) AS records`,[`${result.persistenceQa.tag}:%`,result.persistenceQa.tag])).rows[0];assert.deepEqual(result.syntheticRows,{candidates:0,records:0});result.allSyntheticRowsAbsent=true;result.ledgerAfter=(await query('SELECT filename,checksum,applied_at FROM public.property_intelligence_schema_migrations ORDER BY filename')).rows;assert.deepEqual(result.ledgerAfter,result.ledgerBefore);result.existingAfter=await existingFingerprint(query,migrationReport.existingTables);assert.deepEqual(result.existingAfter,result.existingBefore);result.existingMetadataDataUnchanged=true;
  result.candidatePopulation=(await query(`SELECT c.priority_band,c.candidate_status,c.score_version,count(*)::int AS n FROM public.opportunity_candidates c WHERE EXISTS(SELECT 1 FROM public.opportunity_record_links l JOIN public.discovery_records r ON r.id=l.discovery_record_id JOIN public.discovery_sources s ON s.id=r.discovery_source_id WHERE l.candidate_id=c.id AND s.source_file_hash=$1) GROUP BY c.priority_band,c.candidate_status,c.score_version ORDER BY c.priority_band`,[migrationReport.sourcePlan.ptsSha256])).rows;assert.deepEqual(result.candidatePopulation.map(r=>[r.priority_band,r.candidate_status,r.score_version,r.n]),[['HIGH_REVIEW_PRIORITY','NEEDS_ADDRESS','kern-screen-v1',312],['LOW_REVIEW_PRIORITY','NEEDS_ADDRESS','kern-screen-v1',10303],['MEDIUM_REVIEW_PRIORITY','NEEDS_ADDRESS','kern-screen-v1',701]]);
  await query('ROLLBACK');inTransaction=false;result.status='PASS';result.stage='GATE_12_COMPLETE_GATE_13_STOP';result.nextAction='STOP_FOR_RECONCILED_IMPORT_REVIEW';
}catch(e){result.stage=stage;result.error=/^[A-Z0-9_]+$/.test(e.message??'')?e.message:'SANITIZED_GATE12_FAILURE';result.sqlState=/^[0-9A-Z]{5}$/.test(e.code??'')?e.code:null;result.assertionName=e.name==='AssertionError'?'ASSERTION_FAILED':undefined;if(inTransaction){try{await query('ROLLBACK');}catch{}result.failureRollback=true;}process.exitCode=1;}
finally{client?.release();await db?.close();}
await writeFile(reportPath,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,stage:result.stage,error:result.error,assertionName:result.assertionName,migrationInvocations:result.migrationInvocations,providerCalls:result.providerCalls,databaseQueryCalls:result.databaseQueryCalls,postRollbackCounts:result.postRollbackCounts},null,2));
