export const escape=value=>String(value??'Not supplied').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=value=>value==null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value));
const text=value=>value==null||value===''?'Not supplied':typeof value==='boolean'?(value?'Yes':'No'):String(value);
const label=value=>String(value).replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');
const pct=value=>value==null?'Unknown':new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:4}).format(Number(value));
function leaves(value,prefix=''){
  if(value==null)return [[prefix||'Status','Not supplied']];
  if(typeof value!=='object')return [[label(prefix),text(value)]];
  return Object.entries(value).flatMap(([key,item])=>leaves(item,`${prefix}${prefix?' / ':''}${key}`));
}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${(rows.length?rows:[headers.map((_,i)=>i?'Not supplied':'Status')]).map(row=>`<tr>${row.map(cell=>`<td>${escape(text(cell))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const pairs=rows=>table(['Measure / source field','Persisted value'],rows);
function section(title,body){return `<section data-title="${escape(title)}"><h2>${escape(title)}</h2>${body}</section>`;}
function compsTable(comps){return table(['Address / status','Price / label','Miles / SF','Beds / baths / year'],comps.map(c=>[`${text(c.address)} · ${text(c.status)}`,`${money(c.price)} · ${text(c.price_label??c.priceLabel)}`,`${text(c.distance_miles??c.distanceMiles)} / ${text(c.square_feet??c.squareFeet)}`,`${text(c.bedrooms)} / ${text(c.bathrooms)} / ${text(c.year_built??c.yearBuilt)}`]));}
function scale(title,items){
  const valid=items.filter(([,n])=>n!=null&&Number.isFinite(Number(n)));
  if(valid.length<2)return `<p>${escape(title)}: Not available — insufficient supplied values.</p>`;
  const values=valid.map(([,n])=>Number(n)),lo=Math.min(...values),hi=Math.max(...values);
  // Coordinates are presentation geometry only; monetary values are never calculated here.
  return `<div class="scale"><p>${escape(title)}</p><svg viewBox="0 0 620 ${valid.length*30+12}" role="img" aria-label="${escape(title)}">${valid.map(([name,n],i)=>`<text x="0" y="${i*30+21}" font-size="11">${escape(name)}</text><line x1="190" x2="390" y1="${i*30+17}" y2="${i*30+17}" stroke="#c4d3d0"/><circle cx="${190+(hi===lo?100:(Number(n)-lo)/(hi-lo)*200)}" cy="${i*30+17}" r="4" fill="#25665d"/><text x="410" y="${i*30+21}" font-size="11">${escape(money(n))}</text>`).join('')}</svg></div>`;
}

export function investmentHtml(m){
  const d=m.maoDecision,e=m.economics.base,v=m.valuation,enc=m.encumbrances;
  const acquisition=[['Seller ask',money(d.sellerAskingPrice)],['Target offer',money(d.targetOffer)],['Selected MAO',money(d.calculatedMao)],['Walk-Away Price',money(d.effectiveWalkawayPrice)],['Selected exit basis',d.selectedExitBasis],['Selected exit value',money(d.selectedExitValue)],['Selected hurdle',`${text(d.hurdle.type)} / ${pct(d.hurdle.rate)}`],['Independent low / point / high',`${money(v.low)} / ${money(v.price)} / ${money(v.high)}`],['Known encumbrances',money(enc.knownTotal)],['Unknown encumbrance count',text(enc.unknownCount)],['Decision cost completeness',d.costCompleteness]];
  const body=[
    section('Investment Analysis',`<p class="kicker">PROPERTY INTELLIGENCE · FIX & FLIP</p><h1>${escape(m.property.address)}</h1><p>Generated ${escape(m.reportMeta.generatedAt)} · Historical snapshot presentation</p>${pairs(acquisition.slice(2,5))}<p>Independent evidence and analyst assumptions retain their source status. Unknown costs remain excluded, not zero.</p>`),
    section('Executive Acquisition Summary',pairs([...acquisition,['Rehab total',money(m.rehab?.totalRehabCost??m.rehab?.total)],['Modeled cash invested',money(e.scenarioCashInvested)],['Modeled profit',money(e.modeledProfit)],['Cash-on-cash',pct(e.cashOnCash)],['Break-even sale price',money(m.economics.breakEven?.salePrice??m.economics.breakEven?.breakEvenSalePrice)],['Hold days',e.modeledHoldingDays??e.holdDays??m.economics.costModel?.holdDays??null]])+table(['Unresolved material diligence'],m.diligence.slice(0,6).map(q=>[q.question??q.text??q]))),
    section('Property Intelligence',`<p>Provider-reported — review recommended. No independent physical inspection is implied.</p>`+pairs(leaves(m.propertyDetails))),
    section('Valuation & Exit Evidence',pairs([['Independent low',money(v.low)],['Independent point',money(v.price)],['Independent high',money(v.high)],['Selected basis',d.selectedExitBasis],['Selected exit',money(d.selectedExitValue)],['Source',m.evidenceSummary.source],['Retrieved',m.evidenceSummary.retrievedAt]])+scale('Independent valuation range',[['Low',v.low],['Point',v.price],['High',v.high]])+table(['Exit basis','Value','Evidence / conflict'],(d.exitResults??[]).map(x=>[x.exitBasis,money(x.exitValue),`${text(x.exitEvidenceStatus)} / ${x.exitConflict?'Conflicting: outside supplied independent range':'No conflict recorded'}`]))),
    section('Comparable Properties',`<p>${escape(m.comparables.selection)} Map not included: no existing reliable offline map image is linked.</p>`+compsTable(m.comparables.primary)),
    section('Acquisition & Encumbrances',`<p>${escape(m.methodology.limitations[2])}</p><p>Reported mortgage amounts are not verified payoffs unless explicitly marked.</p>`+pairs([['Seller ask',money(d.sellerAskingPrice)],['Auction minimum',money(d.auctionMinimum)],['Known total',money(enc.knownTotal)],['Unknown count',enc.unknownCount],['Persisted gap versus MAO',money(enc.gap)]])+table(['Type / amount status','Amount','Source / as of','Payoff / priority verified','Notes'],enc.items.map(x=>[`${text(x.type)} / ${text(x.amountStatus)}`,money(x.amount),`${text(x.source)} / ${text(x.asOfDate)}`,`${text(x.payoffVerified)} / ${text(x.priorityKnown)}`,x.notes]))),
    section('Condition & Rehabilitation',`<p>${m.condition.items.length?escape(m.condition.limitation):'Property condition has not been assessed.'}</p>`+table(['Category / condition','Cost','Source','Notes'],m.condition.items.map(x=>[`${text(x.category)} / ${text(x.conditionStatus??x.status)}`,x.estimatedCost==null?'Cost not supplied':money(x.estimatedCost),x.source,x.notes]))+pairs(leaves(m.rehab))),
    section('Investment Economics',`<p>Exact Analysis Snapshot ${escape(m.reportMeta.analysisSnapshotId)}. Decision economics are not substituted.</p>`+pairs([['Modeled proceeds',money(e.modeledProceeds)],['Cash invested',money(e.scenarioCashInvested)],['Total project cost (if defined)',money(e.totalProjectCost??e.modeledProjectCost)],['Modeled profit',money(e.modeledProfit)],['Cash-on-cash',pct(e.cashOnCash)],['Break-even',money(m.economics.breakEven?.salePrice??m.economics.breakEven?.breakEvenSalePrice)],['Completeness',e.costCompleteness]])+pairs(leaves(e.includedCosts??m.economics.costModel))+(e.excludedUnknownCosts?.length?pairs(leaves(e.excludedUnknownCosts)):'')+(m.economics.warnings.length?table(['Excluded unknowns / warnings'],m.economics.warnings.map(x=>[x])):'')),
    section('Maximum Allowable Offer',`<p>${escape(m.methodology.limitations[4])}</p>`+pairs([['Hurdle definition',m.methodology.hurdleDefinition],['Required rate',pct(d.hurdle.rate)],...(d.exitResults??[]).map(x=>[`${x.exitBasis} MAO`,money(x.calculatedMao)]),...acquisition.slice(0,6),['Known obligations / gap',`${money(enc.knownTotal)} / ${money(enc.gap)}`],['Completeness',d.costCompleteness]])+scale('Negotiation scale',[['Target',d.targetOffer],['MAO',d.calculatedMao],['Walk-Away',d.effectiveWalkawayPrice],['Seller ask',d.sellerAskingPrice]])+table(['Material unknowns / warnings'],(d.warnings??[]).map(x=>[x]))),
    section('Sensitivity / Downside',`<p>Persisted deterministic cases. No probability or newly calculated scenario.</p>`+table(['Exit basis','Exit value','Rehab case','MAO','Status / completeness'],m.sensitivity.mao.map(x=>[x.exitBasis,money(x.exitValue),x.rehabCase,money(x.calculatedMao),`${text(x.status)} / ${text(x.costCompleteness)}`]))+table(['Analysis scenario','Proceeds','Profit','Return','Status'],m.scenarios.map(x=>[x.label??x.name??x.id,money(x.outputs?.modeledProceeds),money(x.outputs?.modeledProfit),pct(x.outputs?.cashOnCash),x.outputs?.costCompleteness??x.status]))+pairs(leaves(m.sensitivity.analysis))),
    section('Evidence & Due Diligence',pairs(leaves(m.evidenceSummary))+table(['Group','Question','Status'],m.diligence.map(x=>typeof x==='string'?['Other',x,'Needs verification']:[x.group??x.category??'Other',x.question??x.text,x.status??'Needs verification']))),
    section('Sources & Methodology',pairs(leaves(m.sources))+pairs(leaves(m.methodology))+pairs(leaves(m.reportMeta))),
    section('Appendix — All Retained Comparables',compsTable(m.comparables.all)),
    section('Appendix — Detailed Evidence & Claims',pairs(leaves(m.deal.claims))+(Object.keys(m.valuation).some(k=>!['low','price','high'].includes(k))?pairs(leaves(Object.fromEntries(Object.entries(m.valuation).filter(([k])=>!['low','price','high'].includes(k))))):''))
  ].join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Investment Analysis</title><style>
  @page{size:Letter;margin:0}*{box-sizing:border-box}body{margin:0;color:#233530;font:10pt Arial,sans-serif;line-height:1.4;font-variant-numeric:tabular-nums}.page{width:8.5in;height:11in;padding:50px 48px 48px;position:relative;break-after:page}.page:last-child{break-after:auto}.content{height:942px}header,footer{position:absolute;left:48px;right:48px;font-size:8pt;color:#48625b;display:flex;justify-content:space-between;gap:12px}header{top:20px}footer{bottom:19px}h1{font-size:20pt;font-weight:600;margin:8px 0 15px}h2{font-size:14pt;color:#225e53;border-bottom:1px solid #b9cdc7;padding:8px 0 5px;margin:10px 0}p{margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}.kicker{font-size:9pt;letter-spacing:1px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9pt;margin:8px 0}th{text-align:left;background:#eaf0ee;border-bottom:1px solid #9bb5ac}td,th{padding:6px 7px;vertical-align:top;overflow-wrap:anywhere;white-space:pre-wrap}td{border-bottom:1px solid #dbe4e0}tr{break-inside:avoid}thead{display:table-header-group}svg{width:100%;display:block}.scale{break-inside:avoid;margin:10px 0}#source{width:720px}.continued{font-size:9pt;font-weight:normal}
  td,th{padding:4px 6px}
  </style></head><body><main id="source">${body}</main></body></html>`;
}
