import assert from 'node:assert/strict';
import {calculateAcquisitionDecision,evaluateMao,solveMao} from '../src/underwriting/mao.js';
import {writeJson} from '../src/io/files.js';

const base=overrides=>({strategy:'FIX_AND_FLIP',hurdle:{type:'CASH_ON_CASH',rate:.2},exitBases:[{basis:'INDEPENDENT_LOW',value:180000,evidenceSnapshotId:'00000000-0000-4000-8000-000000000001',evidenceStatus:'INDEPENDENT_ONLY'},{basis:'INDEPENDENT_POINT',value:200000,evidenceSnapshotId:'00000000-0000-4000-8000-000000000001',evidenceStatus:'INDEPENDENT_ONLY'},{basis:'INDEPENDENT_HIGH',value:220000,evidenceSnapshotId:'00000000-0000-4000-8000-000000000001',evidenceStatus:'INDEPENDENT_ONLY'}],acquisitionCosts:[],dispositionCosts:[{name:'seller closing',basis:'FIXED',amount:2000}],rehab:{items:[{category:'ROOF',conditionStatus:'MODERATE',estimatedCost:20000,source:'CONTRACTOR_ESTIMATE'}],contingency:{basis:'PERCENT_OF_REHAB',value:10}},holdingCosts:[{name:'taxes',basis:'FIXED',amount:1000},{name:'utilities',basis:'PER_DAY',amount:10}],holdDays:60,financing:{mode:'CASH'},...overrides});
const results=[];
function check(name,fn){fn();results.push(name);}

for(const type of ['CASH_ON_CASH','RETURN_ON_TOTAL_PROJECT_COST','PROFIT_MARGIN_ON_SALE'])check(`${type} exact threshold`,()=>{const input=base({hurdle:{type,rate:.2}}),decision=calculateAcquisitionDecision(input),result=decision.exitResults.find(item=>item.exitBasis==='INDEPENDENT_POINT');assert.equal(result.status,'AVAILABLE');assert.equal(result.calculatedMao,result.purchasePrice);assert.equal(evaluateMao(input,{exitValue:200000,purchasePrice:result.calculatedMao}).meetsHurdle,true);assert.equal(evaluateMao(input,{exitValue:200000,purchasePrice:result.calculatedMao+.01}).meetsHurdle,false);});
check('fixed, purchase and exit percentage costs',()=>{const input=base({acquisitionCosts:[{name:'buyer closing',basis:'FIXED',amount:1000},{name:'buyer transfer',basis:'PERCENT_OF_PURCHASE',amount:2}],dispositionCosts:[{name:'commission',basis:'PERCENT_OF_EXIT',amount:6}],rehab:{noRehabAssumption:true}}),result=calculateAcquisitionDecision(input).exitResults[1];assert.ok(result.calculatedMao>0);assert.equal(evaluateMao(input,{exitValue:200000,purchasePrice:result.calculatedMao}).meetsHurdle,true);});
check('per-day and per-month costs',()=>{const input=base({holdingCosts:[{name:'security',basis:'PER_DAY',amount:5},{name:'hoa',basis:'PER_MONTH',amount:100}],holdDays:60}),a=calculateAcquisitionDecision(input),b=calculateAcquisitionDecision({...input,holdDays:90});assert.ok(a.calculatedMao>b.calculatedMao);});
check('explicit zero differs from unknown',()=>{const zero=calculateAcquisitionDecision(base({holdingCosts:[{name:'taxes',basis:'FIXED',amount:0}],holdDays:60})),unknown=calculateAcquisitionDecision(base({holdingCosts:[{name:'taxes',basis:'FIXED',amount:null,status:'UNKNOWN'}],holdDays:60}));assert.equal(zero.costCompleteness,'COMPLETE');assert.equal(unknown.costCompleteness,'INCOMPLETE');assert.ok(unknown.warnings.length);});
check('incomplete and unavailable gates',()=>{assert.equal(calculateAcquisitionDecision(base({rehab:{items:[]}})).status,'UNAVAILABLE');const {acquisitionCosts,...withoutAcquisition}=base();assert.equal(calculateAcquisitionDecision(withoutAcquisition).status,'UNAVAILABLE');});
check('encumbrances are separate and gap is neutral',()=>{const without=calculateAcquisitionDecision(base()),withEnc=calculateAcquisitionDecision(base({encumbrances:[{type:'FIRST_MORTGAGE',amount:50000,amountStatus:'REPORTED',source:'SPONSOR'},{type:'TAX_LIEN',amount:null,amountStatus:'UNKNOWN',source:'SPONSOR'}],sellerAskingPrice:100000}));assert.equal(without.calculatedMao,withEnc.calculatedMao);assert.equal(withEnc.knownEncumbranceTotal,50000);assert.equal(withEnc.unknownEncumbranceCount,1);assert.equal(withEnc.apparentSellerEquityAtAsk,50000);});
check('conflict and sensitivity retain evidence bases',()=>{const decision=calculateAcquisitionDecision(base({analystExit:300000,sponsorExit:150000,targetPolicy:{type:'PERCENT_DISCOUNT_FROM_MAO',percentage:10},manualWalkAwayCap:100000}));assert.equal(decision.exitResults.find(x=>x.exitBasis==='ANALYST_EXIT').exitConflict,true);assert.equal(decision.exitResults.length,5);assert.equal(decision.sensitivity.length,15);assert.equal(decision.effectiveWalkawayPrice,Math.min(decision.calculatedMao,100000));assert.equal(decision.targetOffer,Math.round(decision.calculatedMao*.9*100)/100);});
check('deterministic fingerprint and invalid domains',()=>{const a=calculateAcquisitionDecision(base()),b=calculateAcquisitionDecision(base());assert.equal(a.modelFingerprint,b.modelFingerprint);assert.throws(()=>solveMao(base({hurdle:{type:'CASH_ON_CASH',rate:0}}),{exitValue:200000}),/INVALID_HURDLE_RATE/);assert.throws(()=>calculateAcquisitionDecision(base({rehab:{items:[{category:'ROOF',estimatedCost:-1}]}})),/INVALID_REHAB_COST/);});
const report={at:new Date().toISOString(),status:'PASS',checks:results,providerCalls:0,modelVersion:'sprint5-mao-v1'};await writeJson('data/validation/sprint5-mao-qa.json',report);console.log(JSON.stringify(report,null,2));
