// Post-migration schema certification and rollback-only synthetic linkage QA.
// This script never links 3484 Haven and never calls a provider.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createDatabase} from '../../src/persistence/db.js';
import {createOpportunityPropertyLink} from '../../src/persistence/opportunityPropertyLinkRepository.js';
import {deriveOpportunityWorkflow} from '../../src/persistence/assessorOpportunityRepository.js';
import {digest,certifiedChecksums,verifiedClient} from './certification.js';

const report={status:'STOP',mode:'PRODUCTION_006_SCHEMA_CERTIFICATION_ROLLBACK_QA',migrationInvocations:1,providerCalls:0,googleCalls:0,countyNetworkCalls:0,real3484LinkWrites:0};
const packetPath='data/validation/sprint6_3_3-reconciliation-dry-run.json';
const protectedTables=['properties','evidence_snapshots','opportunity_candidates','opportunity_assessor_import_batches','opportunity_assessor_enrichments','candidate_address_resolutions'];
const migrationNames=['001_persistent_intelligence.sql','002_acquisition_decisions.sql','003_opportunity_discovery.sql','004_kern_assessor_opportunity_enrichment.sql','005_candidate_address_resolutions.sql','006_opportunity_property_links.sql'];
let db,client,transaction=false;
const safeError=e=>({code:/^[A-Z0-9_]+$/.test(e?.message??'')?e.message:'SANITIZED_PRODUCTION_CERTIFICATION_STOP',sqlState:/^[0-9A-Z]{5}$/.test(e?.code??'')?e.code:null});
async function protectedSnapshot(q){const rows=[];for(const name of protectedTables){const r=(await q(`SELECT count(*)::int AS count,md5(COALESCE(string_agg(h,'' ORDER BY h),'')) AS fingerprint FROM (SELECT md5(row_to_json(t)::text) AS h FROM public."${name}" t) safe`)).rows[0];rows.push({table:name,count:Number(r.count),fingerprint:r.fingerprint});}return {sha256:digest(JSON.stringify(rows)),rows};}
async function expectedSqlError(q,sql,values,code){await q('SAVEPOINT expected_error');let failed=false;try{await q(sql,values);}catch(e){failed=true;assert.equal(e.message===code||e.code===code,true,`EXPECTED_${code}`);}finally{await q('ROLLBACK TO SAVEPOINT expected_error');await q('RELEASE SAVEPOINT expected_error');}assert.ok(failed,`EXPECTED_${code}`);}
async function expectedRepoError(tx,params,code){let failed=false;try{await createOpportunityPropertyLink(tx,params);}catch(e){failed=true;assert.equal(e.message,code);}assert.ok(failed,`EXPECTED_${code}`);}
try{
  try{process.loadEnvFile('.env');}catch(e){if(e.code!=='ENOENT')throw new Error('ENV_LOAD_STOP');}
  const packet=JSON.parse(await readFile(packetPath,'utf8'));const sql=await readFile('netlify/database/migrations/006_opportunity_property_links.sql','utf8');assert.equal(digest(sql),certifiedChecksums['006_opportunity_property_links.sql'],'MIGRATION_006_CHECKSUM_STOP');
  db=createDatabase();if(!db)throw new Error('DATABASE_NOT_CONFIGURED');client=await verifiedClient(db);report.tls={encrypted:true,authorized:true,protocol:client.connection.stream.getProtocol?.()??null};const q=(text,values=[])=>client.query(text,values);await q('BEGIN READ ONLY');await q("SELECT set_config('search_path','public,pg_catalog',true)");const ns=(await q('SELECT current_schema() AS current,current_schemas(false) AS schemas')).rows[0];assert.equal(ns.current,'public');assert.ok(ns.schemas.includes('public'));report.namespace=ns;
  const ledger=(await q('SELECT filename,checksum,applied_at FROM public.property_intelligence_schema_migrations ORDER BY filename')).rows;assert.deepEqual(ledger.map(r=>r.filename),migrationNames,'LEDGER_ORDER_STOP');assert.deepEqual(ledger.map(r=>r.checksum),migrationNames.map(n=>certifiedChecksums[n]),'LEDGER_CHECKSUM_STOP');report.ledger=ledger;
  const table=(await q("SELECT tablename,rowsecurity FROM pg_tables WHERE schemaname='public' AND tablename='opportunity_property_links'")).rows[0];assert.deepEqual(table,{tablename:'opportunity_property_links',rowsecurity:true},'LINK_TABLE_STOP');const columns=(await q("SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='opportunity_property_links' ORDER BY ordinal_position")).rows;const expectedColumns=['id','candidate_id','property_id','address_resolution_id','assessor_enrichment_id','origin','link_method','link_status','created_at','superseded_at','created_by_context','idempotency_key'];assert.deepEqual(columns.map(c=>c.column_name),expectedColumns);const indexes=(await q("SELECT indexname,indexdef FROM pg_indexes WHERE schemaname='public' AND tablename='opportunity_property_links' ORDER BY indexname")).rows;for(const name of ['opportunity_property_links_pkey','opportunity_property_links_active_candidate_idx','opportunity_property_links_active_property_idx','opportunity_property_links_idempotency_idx','opportunity_property_links_history_idx'])assert.ok(indexes.some(i=>i.indexname===name),`LINK_INDEX_${name}`);for(const name of ['opportunity_property_links_active_candidate_idx','opportunity_property_links_active_property_idx','opportunity_property_links_idempotency_idx'])assert.match(indexes.find(i=>i.indexname===name).indexdef,/UNIQUE/);
  const fks=(await q("SELECT c.conname,t.relname AS target_table,n.nspname AS target_schema,c.confdeltype FROM pg_constraint c JOIN pg_class own ON own.oid=c.conrelid JOIN pg_class t ON t.oid=c.confrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE own.relnamespace='public'::regnamespace AND own.relname='opportunity_property_links' AND c.contype='f' ORDER BY c.conname")).rows;assert.deepEqual(fks.map(f=>f.target_table).sort(),['candidate_address_resolutions','opportunity_assessor_enrichments','opportunity_candidates','properties']);assert.ok(fks.every(f=>f.target_schema==='public'&&f.confdeltype==='r'));const trigger=(await q("SELECT t.tgname,p.prosrc FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_proc p ON p.oid=t.tgfoid WHERE c.relnamespace='public'::regnamespace AND c.relname='opportunity_property_links' AND NOT t.tgisinternal")).rows;assert.equal(trigger.length,1);const certifiedBody=sql.split('CREATE FUNCTION guard_opportunity_property_link() RETURNS trigger LANGUAGE plpgsql AS $$')[1].split('$$;')[0];assert.equal(trigger[0].prosrc,certifiedBody,'LINK_TRIGGER_BODY_STOP');const grants=(await q("SELECT c.relname,a.privilege_type FROM pg_class c CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,acldefault('r',c.relowner))) a LEFT JOIN pg_roles r ON r.oid=a.grantee WHERE c.relnamespace='public'::regnamespace AND c.relname='opportunity_property_links' AND (a.grantee=0 OR r.rolname IN ('anon','authenticated'))")).rows;assert.equal(grants.length,0);assert.equal((await q("SELECT count(*)::int AS n FROM pg_policies WHERE schemaname='public' AND tablename='opportunity_property_links'")).rows[0].n,0);assert.equal((await q('SELECT count(*)::int AS n FROM public.opportunity_property_links')).rows[0].n,0);report.schema={columns:columns.map(c=>({name:c.column_name,type:c.data_type,nullable:c.is_nullable})),indexes:indexes.map(i=>i.indexname),foreignKeys:fks,triggers:['opportunity_property_link_guard'],rls:true,publicApiGrants:0,policies:0,initialRows:0};
  const before=JSON.parse(await readFile('data/validation/sprint6_3_3-production-precheck.json','utf8'));assert.equal(before.status,'PASS');report.protectedBefore=before.protectedBefore;const currentBefore=await protectedSnapshot(q);const beforeNonLedger={...before.protectedBefore,rows:before.protectedBefore.rows.filter(r=>r.table!=='property_intelligence_schema_migrations')};const currentNonLedger={...currentBefore,rows:currentBefore.rows.filter(r=>r.table!=='property_intelligence_schema_migrations')};beforeNonLedger.sha256=digest(JSON.stringify(beforeNonLedger.rows));currentNonLedger.sha256=digest(JSON.stringify(currentNonLedger.rows));assert.deepEqual(currentNonLedger,beforeNonLedger,'PROTECTED_BASELINE_CHANGED_STOP');report.existingBefore=currentNonLedger;
  await q('ROLLBACK');transaction=false;
  await q('BEGIN');transaction=true;await q("SELECT set_config('search_path','public,pg_catalog',true)");const tag=`SPRINT6_3_3_LINK_QA_${Date.now()}`;const c1=(await q("INSERT INTO public.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern',$1,'12345678901','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id",[`${tag}:1`])).rows[0].id;const c2=(await q("INSERT INTO public.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern',$1,'12345678902','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id",[`${tag}:2`])).rows[0].id;const c3=(await q("INSERT INTO public.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern',$1,'12345678903','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id",[`${tag}:3`])).rows[0].id;
  const p1=(await q("INSERT INTO public.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('1 QA ST BAKERSFIELD CA 93301','1 QA ST','BAKERSFIELD','CA','93301') RETURNING id")).rows[0].id;const p2=(await q("INSERT INTO public.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('2 QA ST BAKERSFIELD CA 93301','2 QA ST','BAKERSFIELD','CA','93301') RETURNING id")).rows[0].id;const p3=(await q("INSERT INTO public.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('9 QA ST BAKERSFIELD CA 93301','9 QA ST','BAKERSFIELD','CA','93301') RETURNING id")).rows[0].id;
  const source=(await q("INSERT INTO public.discovery_sources(source_type,jurisdiction,source_name,edition,source_file_hash,record_count) VALUES ('QA','Kern','Sprint6.3.3 QA','QA','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1) RETURNING id")).rows[0].id;const record=(await q("INSERT INTO public.discovery_records(discovery_source_id,source_row_number,external_identifier,atn,raw_payload,normalized_payload,record_fingerprint) VALUES ($1,2,'QA-RECORD','12345678901','{}','{}','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb') RETURNING id",[source])).rows[0].id;await q('INSERT INTO public.opportunity_record_links(candidate_id,discovery_record_id,link_type,confidence_basis) VALUES ($1,$2,\'QA\',\'EXACT\')',[c1,record]);const batch=(await q("INSERT INTO public.opportunity_assessor_import_batches(discovery_source_id,pts_source_sha256,assessor_source_edition,assessor_source_date,county_zip_sha256,county_member_sha256,importer_version,candidate_population_sha256,high_population_sha256,candidate_count,exact_count,unmatched_count,status) VALUES ($1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','QA','2026-01-01','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','qa','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',1,0,1,'IMPORTING') RETURNING id",[source])).rows[0].id;const assessor=(await q("INSERT INTO public.opportunity_assessor_enrichments(candidate_id,import_batch_id,source_reference,assessor_source_edition,assessor_source_date,county_zip_sha256,county_member_sha256,source_row_fingerprint,pts_atn_raw,pts_atn_normalized,crosswalk_status,crosswalk_reason,situs_status,base_year_status,county_acres_status,geometry_status) VALUES ($1,$2,'QA','QA','2026-01-01','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc','123-456-78-90-1','12345678901','UNMATCHED','QA','NOT_APPLICABLE','NOT_APPLICABLE','NOT_APPLICABLE','NOT_APPLICABLE') RETURNING id",[c1,batch])).rows[0].id;const address=(await q("INSERT INTO public.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version) VALUES ($1,'1 QA ST','BAKERSFIELD','CA','93301','1 QA ST, BAKERSFIELD, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),1) RETURNING id",[c1])).rows[0].id;
  const tx={query:q};const first=await createOpportunityPropertyLink(tx,{candidateId:c1,propertyId:p1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:`${tag}:1`});assert.equal(first.idempotentReplay,false);const replay=await createOpportunityPropertyLink(tx,{candidateId:c1,propertyId:p1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:`${tag}:1`});assert.equal(replay.idempotentReplay,true);await expectedRepoError(tx,{candidateId:c1,propertyId:p2},'OPPORTUNITY_PROPERTY_CONFLICT');await expectedRepoError(tx,{candidateId:c2,propertyId:p1},'OPPORTUNITY_PROPERTY_CONFLICT');await expectedRepoError(tx,{candidateId:c2,propertyId:p2,addressResolutionId:address},'OPPORTUNITY_ADDRESS_LINK_MISMATCH');await expectedRepoError(tx,{candidateId:c2,propertyId:p2,assessorEnrichmentId:assessor},'OPPORTUNITY_ASSESSOR_LINK_MISMATCH');const a3=(await q("INSERT INTO public.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version) VALUES ($1,'3 QA ST','BAKERSFIELD','CA','93301','3 QA ST, BAKERSFIELD, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),1) RETURNING id",[c3])).rows[0].id;await expectedRepoError(tx,{candidateId:c3,propertyId:p3,addressResolutionId:a3},'OPPORTUNITY_ADDRESS_CONTEXT_MISMATCH');await expectedSqlError(q,"INSERT INTO public.opportunity_property_links(candidate_id,property_id,origin,link_method,link_status) VALUES ($1,'00000000-0000-4000-8000-000000000000','OPPORTUNITY_ANALYSIS_WORKFLOW','EXPLICIT_WORKFLOW_CONTEXT','ACTIVE')",[c3],'23503');
  await q('UPDATE public.opportunity_property_links SET link_status=\'SUPERSEDED\',superseded_at=now() WHERE candidate_id=$1',[c1]);const second=await createOpportunityPropertyLink(tx,{candidateId:c1,propertyId:p1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:`${tag}:2`});assert.equal(second.idempotentReplay,false);await expectedSqlError(q,"UPDATE public.opportunity_property_links SET created_by_context='MUTATED' WHERE id=$1",[first.link.id],'OPPORTUNITY_PROPERTY_LINK_IMMUTABLE');await expectedSqlError(q,'DELETE FROM public.opportunity_property_links WHERE id=$1',[first.link.id],'OPPORTUNITY_PROPERTY_LINK_IMMUTABLE');const history=(await q("SELECT count(*)::int AS total,count(*) FILTER(WHERE link_status='ACTIVE' AND superseded_at IS NULL)::int AS active FROM public.opportunity_property_links WHERE candidate_id=$1",[c1])).rows[0];assert.deepEqual({total:Number(history.total),active:Number(history.active)},{total:2,active:1});assert.equal(deriveOpportunityWorkflow({}).workflowLifecycle,'NEEDS_ADDRESS');assert.equal(deriveOpportunityWorkflow({providerReady:true}).workflowLifecycle,'DISCOVERED');assert.equal(deriveOpportunityWorkflow({canonicalAddress:{verification_status:'ANALYST_CONFIRMED'}}).workflowLifecycle,'ADDRESS_RESOLVED');assert.equal(deriveOpportunityWorkflow({propertyId:p1}).workflowLifecycle,'PROPERTY_SAVED');assert.equal(deriveOpportunityWorkflow({propertyId:p1,dealCount:1}).workflowLifecycle,'DEAL_CREATED');const unchanged=(await q('SELECT candidate_status,priority_band,screening_score,score_version FROM public.opportunity_candidates WHERE id=$1',[c1])).rows[0];assert.deepEqual(unchanged,{candidate_status:'NEEDS_ADDRESS',priority_band:'LOW_REVIEW_PRIORITY',screening_score:35,score_version:'kern-screen-v1'});report.rollbackQa={tag,exactLink:true,idempotentReplay:true,sameCandidateConflict:true,samePropertyConflict:true,addressCoherence:true,assessorCoherence:true,normalizedAddressCoherence:true,restrictiveFk:true,immutableHistory:true,historyRows:2,activeRows:1,lifecycle:['NEEDS_ADDRESS','DISCOVERED','ADDRESS_RESOLVED','PROPERTY_SAVED','DEAL_CREATED'],screeningUnchanged:true,propertyEvidenceUnchanged:true,assessorUnchanged:true,canonicalAddressUnchanged:true,providerCalls:0};
  await q('ROLLBACK');
  transaction=false;
  const after=await protectedSnapshot(q);
  const afterNonLedger={...after,rows:after.rows.filter(r=>r.table!=='property_intelligence_schema_migrations')};
  afterNonLedger.sha256=digest(JSON.stringify(afterNonLedger.rows));
  assert.deepEqual(afterNonLedger,report.existingBefore,'PROTECTED_DATA_CHANGED_STOP');
  const ledgerCount=(await q('SELECT count(*)::int AS n FROM public.property_intelligence_schema_migrations')).rows[0].n;
  assert.equal(Number(ledgerCount),6);
  const linkRows=(await q('SELECT count(*)::int AS n FROM public.opportunity_property_links')).rows[0].n;
  assert.equal(Number(linkRows),0);
  report.postRollback={lineageRows:0,syntheticAbsent:true,protectedUnchanged:true,'3484Unlinked':true};
  report.status='PASS';report.completedAt=new Date().toISOString();client.release();await db.close();db=null;
}catch(error){report.error=safeError(error);process.exitCode=1;try{if(transaction)await client?.query('ROLLBACK');}catch{}try{client?.release();await db?.close();}catch{} }
await writeFile('data/validation/sprint6_3_3-production-certification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
