// Sprint 6.3.3 isolated certification. No production DDL, data writes, or
// provider calls occur here. The temporary schema is created and removed in a
// single PostgreSQL transaction.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createDatabase} from '../../src/persistence/db.js';
import {createOpportunityPropertyLink} from '../../src/persistence/opportunityPropertyLinkRepository.js';
import {deriveOpportunityWorkflow} from '../../src/persistence/assessorOpportunityRepository.js';
import {migrations,qaName,quotedSchema,verifiedClient,setNamespace,digest} from './certification.js';

const report={status:'STOP',mode:'ISOLATED_001_006_CERTIFICATION',productionWrites:0,productionMigrationApplied:false,providerCalls:0,googleCalls:0,countyNetworkCalls:0};
const protectedTables=['properties','evidence_snapshots','opportunity_candidates','opportunity_assessor_import_batches','opportunity_assessor_enrichments','candidate_address_resolutions','property_intelligence_schema_migrations'];
let db,client,transaction=false,schema,quoted,created=false;
const safeError=e=>({code:/^[A-Z0-9_]+$/.test(e?.message??'')?e.message:'SANITIZED_CERTIFICATION_FAILURE',sqlState:/^[0-9A-Z]{5}$/.test(e?.code??'')?e.code:null});
async function publicSnapshot(q){
  const rows=[];for(const name of protectedTables){const r=(await q(`SELECT count(*)::int AS count,md5(COALESCE(string_agg(h,'' ORDER BY h),'')) AS fingerprint FROM (SELECT md5(row_to_json(t)::text) AS h FROM public."${name}" t) safe`)).rows[0];rows.push({table:name,count:Number(r.count),fingerprint:r.fingerprint});}
  return {sha256:digest(JSON.stringify(rows)),rows};
}
async function expectSqlError(q,sql,values,code){await q('SAVEPOINT expected_error');let failed=false;try{await q(sql,values);}catch(e){failed=true;assert.equal(e.message===code||e.code===code,true,`EXPECTED_${code}`);}finally{await q('ROLLBACK TO SAVEPOINT expected_error');await q('RELEASE SAVEPOINT expected_error');}assert.equal(failed,true,`EXPECTED_${code}`);}
async function expectRepoError(tx,params,code){let failed=false;try{await createOpportunityPropertyLink(tx,params);}catch(e){failed=true;assert.equal(e.message,code);}assert.equal(failed,true,`EXPECTED_${code}`);}
try{
  try{process.loadEnvFile('.env');}catch(e){if(e.code!=='ENOENT')throw new Error('ENV_LOAD_STOP');}
  const input=await migrations();report.migrations=input.map(({filename,checksum})=>({filename,checksum}));assert.equal(input.length,6);
  db=createDatabase();if(!db)throw new Error('DATABASE_NOT_CONFIGURED');client=await verifiedClient(db);report.tls={encrypted:true,authorized:true,protocol:client.connection.stream.getProtocol?.()??null};const q=(sql,values=[])=>client.query(sql,values);
  await q('BEGIN');transaction=true;await q("SET LOCAL statement_timeout='120000'");await q("SET LOCAL lock_timeout='5000'");await setNamespace(client,'pg_catalog');report.publicBefore=await publicSnapshot(q);schema=qaName();quoted=quotedSchema(schema);await q(`CREATE SCHEMA ${quoted}`);created=true;await q(`REVOKE ALL ON SCHEMA ${quoted} FROM PUBLIC`);await q(`CREATE TABLE ${quoted}.property_intelligence_schema_migrations (filename text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())`);
  await setNamespace(client,quoted);const ns=(await q('SELECT current_schema() AS current,current_schemas(false) AS schemas')).rows[0];assert.equal(ns.current,schema);assert.ok(ns.schemas.includes(schema));report.qaNamespace={schema,currentSchema:ns.current,currentSchemas:ns.schemas};
  for(const migration of input){await setNamespace(client,quoted);await q(migration.sql);await q(`INSERT INTO ${quoted}.property_intelligence_schema_migrations(filename,checksum) VALUES ($1,$2)`,[migration.filename,migration.checksum]);}
  await setNamespace(client,quoted);const ledger=(await q(`SELECT filename,checksum FROM ${quoted}.property_intelligence_schema_migrations ORDER BY filename`)).rows;assert.deepEqual(ledger,report.migrations,'LEDGER_CHECKSUM_STOP');
  const table=(await q("SELECT tablename,rowsecurity FROM pg_tables WHERE schemaname=$1 AND tablename='opportunity_property_links'",[schema])).rows[0];assert.ok(table&&table.rowsecurity,'LINK_TABLE_RLS_STOP');
  const columns=(await q("SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema=$1 AND table_name='opportunity_property_links' ORDER BY ordinal_position",[schema])).rows;const expectedColumns=['id','candidate_id','property_id','address_resolution_id','assessor_enrichment_id','origin','link_method','link_status','created_at','superseded_at','created_by_context','idempotency_key'];assert.deepEqual(columns.map(c=>c.column_name),expectedColumns,'LINK_COLUMNS_STOP');assert.ok(columns.every(c=>c.data_type==='uuid'||c.data_type==='text'||c.data_type==='timestamp with time zone'),'LINK_COLUMN_TYPES_STOP');
  const indexes=(await q("SELECT indexname,indexdef FROM pg_indexes WHERE schemaname=$1 AND tablename='opportunity_property_links' ORDER BY indexname",[schema])).rows;for(const name of ['opportunity_property_links_pkey','opportunity_property_links_active_candidate_idx','opportunity_property_links_active_property_idx','opportunity_property_links_idempotency_idx','opportunity_property_links_history_idx'])assert.ok(indexes.some(i=>i.indexname===name),`LINK_INDEX_${name}`);for(const name of ['opportunity_property_links_active_candidate_idx','opportunity_property_links_active_property_idx','opportunity_property_links_idempotency_idx'])assert.match(indexes.find(i=>i.indexname===name).indexdef,/UNIQUE/);
  const fks=(await q("SELECT c.conname,t.relname AS target_table,c.confdeltype FROM pg_constraint c JOIN pg_class own ON own.oid=c.conrelid JOIN pg_class t ON t.oid=c.confrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE own.relnamespace=$1::regnamespace AND own.relname='opportunity_property_links' AND c.contype='f' ORDER BY c.conname",[schema])).rows;assert.deepEqual(fks.map(f=>f.target_table).sort(),['candidate_address_resolutions','opportunity_assessor_enrichments','opportunity_candidates','properties']);assert.ok(fks.every(f=>f.confdeltype==='r'));
  const trigger=(await q("SELECT t.tgname,p.prosrc FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_proc p ON p.oid=t.tgfoid WHERE n.nspname=$1 AND c.relname='opportunity_property_links' AND NOT t.tgisinternal",[schema])).rows;assert.equal(trigger.length,1);assert.match(trigger[0].prosrc,/OPPORTUNITY_PROPERTY_LINK_IMMUTABLE/);assert.match(trigger[0].prosrc,/OPPORTUNITY_PROPERTY_CONFLICT/);assert.match(trigger[0].prosrc,/OPPORTUNITY_ADDRESS_LINK_MISMATCH/);
  const grants=(await q("SELECT c.relname,a.privilege_type FROM pg_class c CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,acldefault('r',c.relowner))) a LEFT JOIN pg_roles r ON r.oid=a.grantee WHERE c.relnamespace=$1::regnamespace AND c.relname='opportunity_property_links' AND (a.grantee=0 OR r.rolname IN ('anon','authenticated'))",[schema])).rows;assert.equal(grants.length,0);assert.equal((await q("SELECT count(*)::int AS n FROM pg_policies WHERE schemaname=$1 AND tablename='opportunity_property_links'",[schema])).rows[0].n,0);assert.equal((await q(`SELECT count(*)::int AS n FROM ${quoted}.opportunity_property_links`)).rows[0].n,0);report.schema={columns:columns.map(c=>({name:c.column_name,type:c.data_type,nullable:c.is_nullable})),indexes:indexes.map(i=>i.indexname),foreignKeys:fks,triggers:['opportunity_property_link_guard'],rls:true,publicApiGrants:0,policies:0,initialRows:0};

  const candidate1=(await q(`INSERT INTO ${quoted}.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern','QA-633-1','12345678901','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id`)).rows[0].id;
  const candidate2=(await q(`INSERT INTO ${quoted}.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern','QA-633-2','12345678902','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id`)).rows[0].id;
  const candidate3=(await q(`INSERT INTO ${quoted}.opportunity_candidates(jurisdiction,candidate_key,atn,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern','QA-633-3','12345678903','PARTIAL','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',35,'kern-screen-v1') RETURNING id`)).rows[0].id;
  const property1=(await q(`INSERT INTO ${quoted}.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('1 QA ST BAKERSFIELD CA 93301','1 QA ST','BAKERSFIELD','CA','93301') RETURNING id`)).rows[0].id;
  const property2=(await q(`INSERT INTO ${quoted}.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('2 QA ST BAKERSFIELD CA 93301','2 QA ST','BAKERSFIELD','CA','93301') RETURNING id`)).rows[0].id;
  const property3=(await q(`INSERT INTO ${quoted}.properties(normalized_address,address_line1,city,state,postal_code) VALUES ('9 QA ST BAKERSFIELD CA 93301','9 QA ST','BAKERSFIELD','CA','93301') RETURNING id`)).rows[0].id;
  const source=(await q(`INSERT INTO ${quoted}.discovery_sources(source_type,jurisdiction,source_name,edition,source_file_hash,record_count) VALUES ('QA','Kern','Sprint6.3.3 QA','QA','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1) RETURNING id`)).rows[0].id;
  const record=(await q(`INSERT INTO ${quoted}.discovery_records(discovery_source_id,source_row_number,external_identifier,atn,raw_payload,normalized_payload,record_fingerprint) VALUES ($1,2,'QA-RECORD','12345678901','{}','{}','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb') RETURNING id`,[source])).rows[0].id;
  await q(`INSERT INTO ${quoted}.opportunity_record_links(candidate_id,discovery_record_id,link_type,confidence_basis) VALUES ($1,$2,'QA','EXACT')`,[candidate1,record]);
  const batch=(await q(`INSERT INTO ${quoted}.opportunity_assessor_import_batches(discovery_source_id,pts_source_sha256,assessor_source_edition,assessor_source_date,county_zip_sha256,county_member_sha256,importer_version,candidate_population_sha256,high_population_sha256,candidate_count,exact_count,unmatched_count,status) VALUES ($1,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','QA','2026-01-01','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','qa','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',1,0,1,'IMPORTING') RETURNING id`,[source])).rows[0].id;
  const assessor=(await q(`INSERT INTO ${quoted}.opportunity_assessor_enrichments(candidate_id,import_batch_id,source_reference,assessor_source_edition,assessor_source_date,county_zip_sha256,county_member_sha256,source_row_fingerprint,pts_atn_raw,pts_atn_normalized,crosswalk_status,crosswalk_reason,situs_status,base_year_status,county_acres_status,geometry_status) VALUES ($1,$2,'QA','QA','2026-01-01','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc','123-456-78-90-1','12345678901','UNMATCHED','QA','NOT_APPLICABLE','NOT_APPLICABLE','NOT_APPLICABLE','NOT_APPLICABLE') RETURNING id`,[candidate1,batch])).rows[0].id;
  const address=(await q(`INSERT INTO ${quoted}.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version) VALUES ($1,'1 QA ST','BAKERSFIELD','CA','93301','1 QA ST, BAKERSFIELD, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),1) RETURNING id`,[candidate1])).rows[0].id;
  const tx={query:q};const first=await createOpportunityPropertyLink(tx,{candidateId:candidate1,propertyId:property1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:'qa-link-1'});assert.equal(first.idempotentReplay,false);const replay=await createOpportunityPropertyLink(tx,{candidateId:candidate1,propertyId:property1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:'qa-link-1'});assert.equal(replay.idempotentReplay,true);
  await expectRepoError(tx,{candidateId:candidate1,propertyId:property2},'OPPORTUNITY_PROPERTY_CONFLICT');await expectRepoError(tx,{candidateId:candidate2,propertyId:property1},'OPPORTUNITY_PROPERTY_CONFLICT');await expectRepoError(tx,{candidateId:candidate2,propertyId:property2,addressResolutionId:address},'OPPORTUNITY_ADDRESS_LINK_MISMATCH');await expectRepoError(tx,{candidateId:candidate2,propertyId:property2,assessorEnrichmentId:assessor},'OPPORTUNITY_ASSESSOR_LINK_MISMATCH');
  const address3=(await q(`INSERT INTO ${quoted}.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version) VALUES ($1,'3 QA ST','BAKERSFIELD','CA','93301','3 QA ST, BAKERSFIELD, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),1) RETURNING id`,[candidate3])).rows[0].id;await expectRepoError(tx,{candidateId:candidate3,propertyId:property3,addressResolutionId:address3},'OPPORTUNITY_ADDRESS_CONTEXT_MISMATCH');await expectSqlError(q,`INSERT INTO ${quoted}.opportunity_property_links(candidate_id,property_id,origin,link_method,link_status) VALUES ($1,'00000000-0000-4000-8000-000000000000','OPPORTUNITY_ANALYSIS_WORKFLOW','EXPLICIT_WORKFLOW_CONTEXT','ACTIVE')`,[candidate3],'23503');
  await q(`UPDATE ${quoted}.opportunity_property_links SET link_status='SUPERSEDED',superseded_at=now() WHERE candidate_id=$1`,[candidate1]);const second=await createOpportunityPropertyLink(tx,{candidateId:candidate1,propertyId:property1,addressResolutionId:address,assessorEnrichmentId:assessor,createdByContext:'QA',idempotencyKey:'qa-link-2'});assert.equal(second.idempotentReplay,false);await expectSqlError(q,`UPDATE ${quoted}.opportunity_property_links SET created_by_context='MUTATED' WHERE id=$1`,[first.link.id],'OPPORTUNITY_PROPERTY_LINK_IMMUTABLE');await expectSqlError(q,`DELETE FROM ${quoted}.opportunity_property_links WHERE id=$1`,[first.link.id],'OPPORTUNITY_PROPERTY_LINK_IMMUTABLE');const history=(await q(`SELECT count(*)::int AS total,count(*) FILTER (WHERE link_status='ACTIVE' AND superseded_at IS NULL)::int AS active FROM ${quoted}.opportunity_property_links WHERE candidate_id=$1`,[candidate1])).rows[0];assert.deepEqual({total:Number(history.total),active:Number(history.active)},{total:2,active:1});
  assert.equal(deriveOpportunityWorkflow({}).workflowLifecycle,'NEEDS_ADDRESS');assert.equal(deriveOpportunityWorkflow({providerReady:true}).workflowLifecycle,'DISCOVERED');assert.equal(deriveOpportunityWorkflow({canonicalAddress:{verification_status:'ANALYST_CONFIRMED'}}).workflowLifecycle,'ADDRESS_RESOLVED');assert.equal(deriveOpportunityWorkflow({propertyId:property1}).workflowLifecycle,'PROPERTY_SAVED');assert.equal(deriveOpportunityWorkflow({propertyId:property1,dealCount:1}).workflowLifecycle,'DEAL_CREATED');const unchanged=(await q(`SELECT candidate_status,priority_band,screening_score,score_version FROM ${quoted}.opportunity_candidates WHERE id=$1`,[candidate1])).rows[0];assert.deepEqual(unchanged,{candidate_status:'NEEDS_ADDRESS',priority_band:'LOW_REVIEW_PRIORITY',screening_score:35,score_version:'kern-screen-v1'});report.rollbackQa={exactLink:true,idempotentReplay:true,sameCandidateConflict:true,samePropertyConflict:true,addressCoherence:true,assessorCoherence:true,normalizedAddressCoherence:true,restrictiveFk:true,immutableHistory:true,historyRows:2,activeRows:1,lifecycle:['NEEDS_ADDRESS','DISCOVERED','ADDRESS_RESOLVED','PROPERTY_SAVED','DEAL_CREATED'],screeningUnchanged:true,providerCalls:0};
  await q('ROLLBACK');transaction=false;created=false;await q('BEGIN');await setNamespace(client,'pg_catalog');const removed=(await q('SELECT to_regnamespace($1) AS namespace',[schema])).rows[0].namespace;assert.equal(removed,null,'QA_SCHEMA_CLEANUP_STOP');report.cleanup={rolledBack:true,schemaRemoved:true};report.publicAfter=await publicSnapshot(q);assert.deepEqual(report.publicAfter,report.publicBefore,'PUBLIC_CHANGED_STOP');await q('ROLLBACK');report.status='PASS';report.completedStage='ISOLATED_REBUILD_CERTIFIED';
}catch(error){report.error=safeError(error);report.failedStage=report.failedStage??'CERTIFICATION';process.exitCode=1;try{if(transaction)await client.query('ROLLBACK');}catch{}if(created&&client)try{await setNamespace(client,'pg_catalog');await client.query(`DROP SCHEMA IF EXISTS ${quoted} CASCADE`);}catch{}}
finally{client?.release();await db?.close();}
await mkdir('data/validation',{recursive:true});await writeFile('data/validation/sprint6_3_3-isolated-schema-certification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
