// Isolated PostgreSQL certification only. Never invokes db:migrate and never targets public.
import {mkdir,writeFile} from 'node:fs/promises';
import {createDatabase} from '../../src/persistence/db.js';
import {migrationInputs631,qaName631,quote631} from './certification.js';
const schema=qaName631(),quoted=quote631(schema,true),report={status:'STOP',mode:'ISOLATED_SCHEMA_ONLY',qaSchema:schema,productionWrites:0,productionMigrationApplied:false,providerCalls:0};
let db,client,active=false,created=false,stage='MIGRATION_REVIEW';
const q=(sql,values=[])=>client.query(sql,values);
try{
  const migrations=await migrationInputs631();report.migrations=migrations.map(({filename,checksum})=>({filename,checksum}));
  try{process.loadEnvFile('.env');}catch(e){if(e.code!=='ENOENT')throw new Error('ENV_LOAD_STOP');}
  db=createDatabase();if(!db)throw new Error('DATABASE_NOT_CONFIGURED');client=await db.getPool().connect();if(!client.connection?.stream?.encrypted||client.connection.stream.authorized!==true)throw new Error('VERIFIED_TLS_REQUIRED');report.tls={encrypted:true,authorized:true};
  await q('BEGIN');active=true;await q("SET LOCAL statement_timeout='60000'");await q("SET LOCAL lock_timeout='5000'");
  await q('SELECT pg_catalog.set_config(\'search_path\',$1,true)',[`${quoted}, pg_catalog`]);
  const permission=(await q("SELECT has_database_privilege(current_database(),'CREATE') AS can_create")).rows[0];if(!permission.can_create)throw new Error('SCHEMA_CREATE_PRIVILEGE_REQUIRED');
  await q(`CREATE SCHEMA ${quoted}`);created=true;await q(`REVOKE ALL ON SCHEMA ${quoted} FROM PUBLIC`);await q(`CREATE TABLE ${quoted}.property_intelligence_schema_migrations (filename text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())`);
  const namespace=(await q('SELECT current_schema() AS current,current_schemas(false) AS schemas')).rows[0];if(namespace.current!==schema||!namespace.schemas.includes(schema))throw new Error('QA_NAMESPACE_RESOLUTION_STOP');report.namespace={currentSchema:namespace.current,currentSchemas:namespace.schemas};
  for(const migration of migrations){stage=`MIGRATION_${migration.filename.slice(0,3)}`;await q("SELECT pg_catalog.set_config('search_path',$1,true)",[`${quoted}, pg_catalog`]);await q(migration.sql);await q(`INSERT INTO ${quoted}.property_intelligence_schema_migrations(filename,checksum) VALUES ($1,$2)`,[migration.filename,migration.checksum]);}
  stage='SCHEMA_CERTIFICATION';const tables=(await q("SELECT tablename,rowsecurity FROM pg_tables WHERE schemaname=$1 ORDER BY tablename",[schema])).rows;const canonical=tables.find(t=>t.tablename==='candidate_address_resolutions');if(!canonical||!canonical.rowsecurity)throw new Error('ADDRESS_TABLE_RLS_STOP');
  const indexes=(await q("SELECT indexname FROM pg_indexes WHERE schemaname=$1 AND tablename='candidate_address_resolutions' ORDER BY indexname",[schema])).rows.map(r=>r.indexname);for(const name of ['candidate_address_resolutions_active_candidate_idx','candidate_address_resolutions_idempotency_idx','candidate_address_resolutions_history_idx'])if(!indexes.includes(name))throw new Error('ADDRESS_INDEX_STOP');
  const triggers=(await q("SELECT t.tgname FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname='candidate_address_resolutions' AND NOT t.tgisinternal",[schema])).rows;if(triggers.length!==1)throw new Error('ADDRESS_TRIGGER_STOP');
  const checks=(await q("SELECT count(*)::int AS n FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname=$1 AND c.conrelid='candidate_address_resolutions'::regclass",[schema])).rows[0].n;if(checks<8)throw new Error('ADDRESS_CONSTRAINT_STOP');
  const ledger=(await q(`SELECT filename,checksum FROM ${quoted}.property_intelligence_schema_migrations ORDER BY filename`)).rows;if(ledger.length!==5||JSON.stringify(ledger)!==JSON.stringify(report.migrations))throw new Error('LEDGER_MISMATCH');report.schema={tableCount:tables.length,canonicalRows:0,indexes,triggers:triggers.map(t=>t.tgname),constraints:checks};
  stage='ADDRESS_BEHAVIOR_QA';await q('SAVEPOINT address_behavior_qa');
  const candidate=(await q(`INSERT INTO ${quoted}.opportunity_candidates(jurisdiction,candidate_key,identity_status,candidate_status,priority_band,screening_score,score_version) VALUES ('Kern','QA-ADDRESS-631','UNRESOLVED','NEEDS_ADDRESS','LOW_REVIEW_PRIORITY',1,'kern-screen-v1') RETURNING id`)).rows[0].id;
  const first=(await q(`INSERT INTO ${quoted}.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version,idempotency_key) VALUES ($1,'1 First St','Bakersfield','CA','93301','1 First St, Bakersfield, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),1,'qa-address-1') RETURNING id`,[candidate])).rows[0].id;
  await q('SAVEPOINT address_unique');let activeRejected=false;try{await q(`INSERT INTO ${quoted}.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version,idempotency_key) VALUES ($1,'2 Second St','Bakersfield','CA','93301','2 Second St, Bakersfield, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),2,'qa-address-2')`,[candidate]);}catch(e){if(e.code!=='23505')throw e;activeRejected=true;await q('ROLLBACK TO SAVEPOINT address_unique');}if(!activeRejected)throw new Error('ADDRESS_ACTIVE_UNIQUENESS_STOP');await q('RELEASE SAVEPOINT address_unique');
  await q(`UPDATE ${quoted}.candidate_address_resolutions SET superseded_at=now(),verification_status='SUPERSEDED' WHERE id=$1`,[first]);const second=(await q(`INSERT INTO ${quoted}.candidate_address_resolutions(candidate_id,street,city,state,postal_code,formatted_address,resolution_source,resolution_method,verification_status,analyst_confirmed,confirmed_at,version,idempotency_key) VALUES ($1,'2 Second St','Bakersfield','CA','93301','2 Second St, Bakersfield, CA 93301','ANALYST','MANUAL_EXTERNAL_LOOKUP','ANALYST_CONFIRMED',true,now(),2,'qa-address-2') RETURNING id`,[candidate])).rows[0].id;
  await q('SAVEPOINT address_delete');let immutableRejected=false;try{await q(`DELETE FROM ${quoted}.candidate_address_resolutions WHERE id=$1`,[second]);}catch(e){if(e.message==='ADDRESS_RESOLUTION_HISTORY_IMMUTABLE'){immutableRejected=true;await q('ROLLBACK TO SAVEPOINT address_delete');}}if(!immutableRejected)throw new Error('ADDRESS_IMMUTABILITY_STOP');await q('RELEASE SAVEPOINT address_delete');const historyCount=(await q(`SELECT count(*)::int AS n FROM ${quoted}.candidate_address_resolutions WHERE candidate_id=$1`,[candidate])).rows[0].n;if(historyCount!==2)throw new Error('ADDRESS_VERSIONING_STOP');report.addressBehavior={activeUniqueness:true,immutableHistory:true,versions:historyCount};await q('ROLLBACK TO SAVEPOINT address_behavior_qa');await q('RELEASE SAVEPOINT address_behavior_qa');
  await q(`DROP SCHEMA ${quoted} CASCADE`);created=false;await q('COMMIT');active=false;report.cleanup={dropped:true};report.status='PASS';report.completedStage='ISOLATED_REBUILD_CERTIFIED';
}catch(error){report.failedStage=stage;report.error=/^[A-Z0-9_]+$/.test(error.message??'')?error.message:'SANITIZED_CERTIFICATION_FAILURE';report.sqlState=/^[0-9A-Z]{5}$/.test(error.code??'')?error.code:null;if(active)try{await q('ROLLBACK');}catch{}if(created&&client)try{await q(`DROP SCHEMA ${quoted} CASCADE`);}catch{}process.exitCode=1;
}finally{client?.release();await db?.close();}
await mkdir('data/validation',{recursive:true});await writeFile('data/validation/sprint6_3_1-isolated-schema-certification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
