import React,{useEffect,useRef,useState} from 'react';
import {action,request} from '../../services/api.js';
const money=v=>v==null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const label=v=>String(v??'Unknown').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const situsNote='County-reported situs; not independently verified as a postal or deliverable address.';
const assessmentNote='County assessment data is tax-roll evidence and is not an independent market valuation.';
const categories=['RESIDENTIAL_SINGLE_FAMILY','RESIDENTIAL_MULTI_FAMILY','MANUFACTURED_MOBILE','VACANT_RESIDENTIAL','VACANT_OTHER','COMMERCIAL','INDUSTRIAL','AGRICULTURAL','GOVERNMENT_EXEMPT','MINERAL','OTHER_UNKNOWN'];
const pairs=items=><dl>{items.map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd style={{overflowWrap:'anywhere'}}>{v??'Unknown'}</dd></React.Fragment>)}</dl>;
export default function Opportunities({onAnalyze}){
  const [active,setActive]=useState(()=>window.location.hash==='#opportunities'),[rows,setRows]=useState([]),[metrics,setMetrics]=useState(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[filters,setFilters]=useState({}),[applied,setApplied]=useState({}),[selected,setSelected]=useState(null),[detailId,setDetailId]=useState(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[resolver,setResolver]=useState(null),[resolverForm,setResolverForm]=useState({street:'',city:'',state:'',postalCode:'',postalCodeExtension:'',analystConfirmed:false}),[resolverBusy,setResolverBusy]=useState(false),[confirmation,setConfirmation]=useState(null);
  const requestId=useRef(0),originatingView=useRef(null),detailHeading=useRef(null),resolverOpened=useRef(false),pageSize=25;
  const queryFor=(f,p=1)=>new URLSearchParams({...Object.fromEntries(Object.entries(f).filter(([,v])=>v!==''&&v!=null)),page:String(p),pageSize:String(pageSize)});
  useEffect(()=>{const h=()=>setActive(window.location.hash==='#opportunities');window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);
  async function load(nextPage=1,f=filters){const id=++requestId.current;setBusy(true);setError('');try{const result=await request(`opportunities?${queryFor(f,nextPage)}`);if(id!==requestId.current)return;setRows(result.opportunities??[]);setTotal(result.total??0);setMetrics(result.metrics??null);setPage(nextPage);setApplied(f);}catch(e){if(id===requestId.current)setError(e.message);}finally{if(id===requestId.current)setBusy(false);}}
  useEffect(()=>{if(active)load(1);},[active]);
  async function open(id,event){originatingView.current=event?.currentTarget??originatingView.current;setDetailId(id);setSelected(null);setDetailError('');setDetailLoading(true);try{const result=await request(`opportunities/${id}`);if(!result.opportunity)throw new Error('NOT_FOUND');setSelected(result.opportunity);}catch(e){setDetailError('Unable to load opportunity detail. The candidate list has not been changed.');}finally{setDetailLoading(false);}}
  function closeDetail(){setDetailId(null);setSelected(null);setDetailError('');setDetailLoading(false);const target=originatingView.current;originatingView.current=null;requestAnimationFrame(()=>target?.focus());}
  useEffect(()=>{if(!detailId&&!resolver)return;const onKey=e=>{if(e.key!=='Escape')return;if(resolver){setResolver(null);resolverOpened.current=false;}else closeDetail();};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[detailId,resolver]);
  useEffect(()=>{if(detailId&&!detailLoading)detailHeading.current?.focus();},[detailId,detailLoading]);
  useEffect(()=>{if(!resolver&&resolverOpened.current){setDetailId(null);setSelected(null);resolverOpened.current=false;}},[resolver]);
  useEffect(()=>{if(!confirmation)return;const onKey=e=>{if(e.key==='Escape'){confirmation.onCancel?.();setConfirmation(null);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[confirmation]);
  function askConfirmation({title,message,confirmLabel='Continue',onConfirm,onCancel}){setConfirmation({title,message,confirmLabel,onConfirm,onCancel});}
  async function acceptConfirmation(){const task=confirmation?.onConfirm;setConfirmation(null);await task?.();}
  async function review(actionName){if(!selected)return;setBusy(true);try{await action(`opportunities/${selected.id}/review`,{action:actionName,requestKey:crypto.randomUUID()});await open(selected.id);await load(page,applied);}catch(e){setError(e.message);}finally{setBusy(false);}}
  function prefill(situs){const text=String(situs??'');const parts=text.split(',').map(v=>v.trim());const tail=(parts[parts.length-1]??'').match(/^([A-Za-z]{2})\s+(\d{5})(?:-(\d{4}))?$/);return {street:parts[0]??'',city:tail?parts.slice(1,-1).join(', '):(parts[1]??''),state:tail?.[1]??'',postalCode:tail?.[2]??'',postalCodeExtension:tail?.[3]??'',analystConfirmed:false};}
  async function openResolver(row){resolverOpened.current=true;setDetailId(null);setResolverBusy(true);try{const result=await request(`opportunities/${row.id}/address-resolution`);const current=result.addressResolution;setResolver({id:row.id,row,countySitus:row.assessor?.situs_raw??null,current,history:result.history??[]});setResolverForm(current?{street:current.street,city:current.city,state:current.state,postalCode:current.postal_code,postalCodeExtension:current.postal_code_extension??'',analystConfirmed:false}:prefill(row.assessor?.situs_raw));}catch(e){setError(e.message);}finally{setResolverBusy(false);}}
  function providerReadyLikely(row){if(row.canonicalAddress)return true;if(row.address_line1&&row.city&&row.state&&row.postal_code)return true;const text=String(row.assessor?.situs_raw??'');return /^\d[^,]{1,180},\s*[^,]{2,80},\s*[A-Za-z]{2}\s+\d{5}(?:-\d{4})?$/.test(text);}
  async function analyze(row){if(busy||!onAnalyze)return;if(row.assessor?.crosswalk_status!=='MATCHED_EXACT'){setError('Only exact county identity matches may be analyzed.');return;}if(!providerReadyLikely(row)){await openResolver(row);return;}askConfirmation({title:'Analyze this property?',message:'This will use the selected address as the starting address and may consume RentCast quota. No request is made until you confirm.',confirmLabel:'Continue to Analyze',onConfirm:async()=>{setBusy(true);try{const result=await onAnalyze(row.id);if(result?.error==='ADDRESS_INCOMPLETE')await openResolver(row);else if(result?.error)setError(result.message);}finally{setBusy(false);}}});}
  async function saveResolution(andAnalyze=false){if(!resolver)return;setResolverBusy(true);setError('');try{const payload={...resolverForm,action:'SAVE',analystConfirmed:true,resolutionSource:'ANALYST',resolutionMethod:'MANUAL_EXTERNAL_LOOKUP',requestKey:crypto.randomUUID()};if(resolver.current)payload.supersedeId=resolver.current.id;await action(`opportunities/${resolver.id}/address-resolution`,payload);if(andAnalyze){const id=resolver.id;askConfirmation({title:'Analyze the saved address?',message:'The canonical address is saved. Continuing may consume RentCast quota; cancel to leave the address saved without making a provider request.',confirmLabel:'Continue to Analyze',onCancel:()=>setResolver(null),onConfirm:async()=>{const analyzed=await onAnalyze(id);if(analyzed?.model){setResolver(null);window.location.hash='overview';}}});return;}setResolver(null);await open(resolver.id);await load(page,applied);}catch(e){setError(e.message);}finally{setResolverBusy(false);}}
  const change=(k,v)=>setFilters(f=>({...f,[k]:v,preset:''}));
  const preset=p=>{const f={preset:p};setFilters(f);load(1,f);};
  const select=(key,title,choices)=><select aria-label={title} value={filters[key]??''} onChange={e=>change(key,e.target.value)}><option value="">All {title.toLowerCase()}</option>{choices.map(v=><option key={v} value={v}>{label(v)}</option>)}</select>;
  if(!active)return null;
  const pages=Math.max(1,Math.ceil(total/pageSize)),a=selected?.assessor;
  return <section id="opportunities" className="opportunities-panel">
    <div className="section-heading"><div><p className="eyebrow">KERN POWER-TO-SELL · INVESTIGATION QUEUE</p><h2>Opportunities</h2><p>Priority indicates where to investigate first, not expected investment return.</p></div><a href={`/api/opportunities/export?${queryFor(applied)}`} download>Export PTS CSV (first 100)</a></div>
    <p className="muted">CSV omits Assessor-derived fields. County evidence is for internal research; retain the county source disclaimer with any permitted extract.</p>
    {metrics&&<div className="metrics">{[['Imported source records',metrics.counts?.records],['Unique candidates',metrics.counts?.candidates],['Needs address',metrics.counts?.needs_address]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v??'—'}</strong></div>)}</div>}
    <div className="fixture-buttons"><button disabled={busy} onClick={()=>preset('HIGH_RESIDENTIAL')}>High Priority — Residential Buildings</button><button disabled={busy} onClick={()=>preset('HIGH_SFR')}>High Priority — Single Family</button><button disabled={busy} onClick={()=>preset('')}>Clear filters</button></div>
    <p className="muted">Presets filter existing priority and PI categories; they do not change scores. Review flags describe data quality, not investment quality.</p>
    <form className="opportunity-filters" style={{display:'flex',flexWrap:'wrap',gap:'0.75rem'}} onSubmit={e=>{e.preventDefault();load(1);}}>
      <input aria-label="Search candidates" value={filters.search??''} onChange={e=>change('search',e.target.value)} placeholder="County situs, ATN or APN9"/>
      {select('priorityBand','Priority band',['HIGH_REVIEW_PRIORITY','MEDIUM_REVIEW_PRIORITY','LOW_REVIEW_PRIORITY'])}
      {select('status','Candidate status',['NEW','REVIEWING','NEEDS_ADDRESS','READY_FOR_ENRICHMENT','ENRICHED','DEAL_CREATED','DEFERRED','REJECTED','ARCHIVED'])}
      {select('assessorStatus','Assessor status',['MATCHED_EXACT','UNMATCHED'])}{select('category','PI category',categories)}{select('sort','Sort opportunities',['priority','amount','updated','atn'])}
      {[['hasSitus','Has County Situs'],['geometry','Geometry Available'],['reviewRequired','Review Required']].map(([k,title])=><label key={k}><input type="checkbox" checked={filters[k]==='true'} onChange={e=>change(k,e.target.checked?'true':'')}/>{title}</label>)}<button disabled={busy}>Apply filters</button>
    </form><p className="muted opportunity-grid-help">Sort is server-side and applies across the paginated result. Priority, delinquency amount, and recently updated sort high-to-low; ATN sorts ascending. Filters remain evidence/status filters and do not change `kern-screen-v1` values.</p>
    {error&&<p role="alert" className="warning">{error}</p>}
    <div className="table-scroll"><table><thead><tr>{['Priority','County Situs / ATN','PI Category','Tax Delinquency','County Net Assessment','Assessor Status','Candidate Status','Property / Deal linkage','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className={selected?.id===row.id?'selected-row':''}><td>{label(row.priority_band)}<small>Score {row.screening_score??'Unknown'}</small></td><td><button className="row-select" onClick={e=>open(row.id,e)}>{row.assessor?.situs_status==='SITUS_PRESENT'?row.assessor.situs_raw:row.atn}</button><small>{row.assessor?.situs_status==='SITUS_PRESENT'?`ATN ${row.atn}`:'County situs unavailable'}</small><small>{row.canonicalAddress?'Address resolved':row.assessor?.situs_status==='SITUS_PRESENT'?'County situs only':'Address unresolved'}</small></td><td>{label(row.assessor?.research_use_category)}</td><td>{money(row.amount_owed)}</td><td>{money(row.assessor?.net_assessment)}</td><td>{label(row.assessor?.crosswalk_status)}</td><td>{label(row.candidate_status)}</td><td>{row.resolved_property_id?<><a href="#saved-properties">Saved Property</a><small>{row.linked_deal_count??0} linked Deals</small></>:'Not linked'}</td><td><button aria-label={`View opportunity ${row.atn}`} onClick={e=>open(row.id,e)}>View</button><button disabled={busy} onClick={()=>analyze(row)}>Analyze Property</button></td></tr>)}{!rows.length&&<tr><td colSpan="9">{busy?'Loading…':'No candidates match the current filters.'}</td></tr>}</tbody></table></div>
    <p className="muted">{situsNote} {assessmentNote}</p>
    <div className="opportunity-pagination"><button disabled={busy||page<=1} onClick={()=>load(page-1,applied)}>Previous</button><span>Page {page} of {pages} · {total.toLocaleString()} candidates</span><button disabled={busy||page>=pages} onClick={()=>load(page+1,applied)}>Next</button></div>
    {detailId&&<div className="opportunity-detail-backdrop" role="presentation" style={resolver?{display:'none'}:undefined}><aside className="opportunity-detail-drawer" role="dialog" aria-modal="true" aria-labelledby="opportunity-detail-title">
      <div className="section-heading"><h3 id="opportunity-detail-title" tabIndex="-1" ref={detailHeading}>{selected?(selected.canonicalAddress?.formatted_address?`Canonical address · ${selected.canonicalAddress.formatted_address}`:`${selected.assessor?.situs_raw??`ATN ${selected.atn}`}`):'Opportunity detail'}</h3><button onClick={closeDetail}>Close</button></div>
      {detailLoading&&<p className="state">Loading opportunity detail…</p>}
      {detailError&&<div role="alert" className="warning"><p>Unable to load opportunity detail. The candidate list has not been changed.</p><div className="create-deal"><button onClick={()=>open(detailId)}>Retry</button><button onClick={closeDetail}>Close</button></div></div>}
      {selected&&<>
        <div className="detail-summary"><span className="badge">{label(selected.priority_band)}</span><span className="badge">Score {selected.screening_score??'Unknown'}</span><span className="badge">{label(selected.assessor?.research_use_category)}</span><span className="badge">{label(selected.candidate_status)}</span><span className="badge">Address: {selected.canonicalAddress?'Resolved':'Not resolved'}</span></div>
        <h4>Distress Signal · existing Power-to-Sell evidence</h4>
        <p>Tax delinquency / parcel amount: <strong>{money(selected.distress?.amountOwed)}</strong></p>
        <p>Investigation priority: {label(selected.distress?.priorityBand)} · Screening score: {selected.distress?.screeningScore??'Unknown'}</p>
        <p>Source: Kern Power-to-Sell · edition/date: {selected.distress?.sourceEdition??'Unknown'} / {selected.distress?.sourceDate?String(selected.distress.sourceDate).slice(0,10):'Unknown'} · page: {selected.distress?.sourcePage??'Unknown'}</p>
        <p className="muted">This is a screening signal, not proof of foreclosure, mortgage default, equity, seller motivation or willingness to sell.</p>
        <h4>County Property Record</h4>
        {!a?<p>Assessor match: Unmatched. County property record is unavailable.</p>:<>{pairs([['PTS ATN',a.pts_atn_raw??a.pts_atn_normalized],['Assessor ATN',a.assessor_atn_raw??a.assessor_atn_normalized],['APN9 / Parcel',a.apn9],['Assessor crosswalk',label(a.crosswalk_status)],['Official County Use Code',a.use_code],['Official County Use Description',a.use_description],['PI Research Category',label(a.research_use_category)],['Assessor source edition/date',`${a.assessor_source_edition??'Unknown'} / ${a.assessor_source_date?String(a.assessor_source_date).slice(0,10):'Unknown'}`]])}</>}
        <h4>County Assessments</h4>
        {!a?<p>Not available without an exact Assessor match.</p>:<>{pairs([['County Land Assessment',money(a.land_assessment)],['County Improvement Assessment',money(a.improvement_assessment)],['County Net Assessment',money(a.net_assessment)],['County Base-Year Value',money(a.base_year_value)]])}<p className="warning">{assessmentNote}</p></>}
        <h4>Parcel / Acreage</h4>
        {!a?<p>Not available without an exact Assessor match.</p>:<>{pairs([['County Roll Acreage',a.county_acres==null?'Unknown':`${a.county_acres} acres · ${label(a.county_acres_status)}`],['Parcel Shape Acreage',a.shape_acres==null?'Unknown':`${a.shape_acres} acres`],['Parcel Shape Square Feet',a.shape_sqft==null?'Unknown':a.shape_sqft],['Geometry Status',label(a.geometry_status)],['Acreage Delta',a.acreage_delta==null?'Unknown':a.acreage_delta]])}{(a.review_flags??[]).includes('ACREAGE_DELTA_GT_0_01')&&<p className="warning">County acreage sources differ; review before relying on lot size.</p>}</>}
        <h4>Address Evidence</h4>
        <p><strong>County Situs</strong>: {a?.situs_raw??'County situs unavailable'} · {label(a?.situs_status)}</p><p>{situsNote}</p>
        <p><strong>Canonical Address</strong>: {selected.canonicalAddress?`${selected.canonicalAddress.formatted_address} · ${label(selected.canonicalAddress.verification_status)} · ${label(selected.canonicalAddress.resolution_source)} / ${label(selected.canonicalAddress.resolution_method)} · analyst confirmed: ${selected.canonicalAddress.analyst_confirmed?'Yes':'No'}`:'Not yet resolved'}</p>
        <h4>Linkage</h4>{pairs([['Property',selected.linkage?.propertyId?'Linked':'Not linked'],['Deal',selected.linkage?.dealCount?`${selected.linkage.dealCount} linked`:'Not linked'],['Canonical Address',selected.linkage?.canonicalAddressId?'Linked':'Not linked']])}
        <details><summary>Data Quality / Review Notes</summary>{a?.review_flags?.length?<ul>{a.review_flags.map(f=><li key={f}>{label(f)}</li>)}</ul>:<p>No additional review notes.</p>}</details>
        <details><summary>Power-to-Sell source records</summary><ul>{selected.records?.map(r=><li key={r.id}>Source row {r.source_row_number}, page {r.source_page??'Unknown'} · {r.edition??'Unknown'} · delinquency {money(r.amount_owed)}</li>)}</ul></details>
        <div className="create-deal"><button onClick={closeDetail}>Close</button><button disabled={busy} onClick={()=>openResolver(selected)}>Resolve Address</button><button disabled={busy} onClick={()=>analyze(selected)}>Analyze Property</button></div>
      </>}
    </aside></div>}
    {resolver&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="resolver-title"><article className="modal resolver-modal"><header className="modal-header"><div><p className="eyebrow">CANONICAL ADDRESS · ANALYST CONFIRMATION</p><h3 id="resolver-title">Confirm canonical property address</h3></div><button className="modal-close" disabled={resolverBusy} onClick={()=>setResolver(null)} aria-label="Close address resolver">×</button></header><div className="modal-body"><p className="modal-intro">County situs is read-only evidence and may be incomplete. ZIP codes are never inferred.</p><div className="county-situs-card"><span>County situs evidence</span><strong>{resolver.countySitus??'Unavailable'}</strong><small>Read-only county evidence · not independently verified as a postal or deliverable address.</small></div><form className="resolver-form" onSubmit={e=>{e.preventDefault();saveResolution(false);}}><div className="resolver-fields"><label>Street<input required value={resolverForm.street} onChange={e=>setResolverForm({...resolverForm,street:e.target.value})}/></label><label>City<input required value={resolverForm.city} onChange={e=>setResolverForm({...resolverForm,city:e.target.value})}/></label><label>State<input required maxLength="2" value={resolverForm.state} onChange={e=>setResolverForm({...resolverForm,state:e.target.value})}/></label><label>ZIP-5<input required pattern="\d{5}" value={resolverForm.postalCode} onChange={e=>setResolverForm({...resolverForm,postalCode:e.target.value})}/></label><label>ZIP+4 <span className="muted">(optional)</span><input pattern="\d{4}" value={resolverForm.postalCodeExtension} onChange={e=>setResolverForm({...resolverForm,postalCodeExtension:e.target.value})}/></label></div><label className="confirm-check"><input type="checkbox" required checked={resolverForm.analystConfirmed} onChange={e=>setResolverForm({...resolverForm,analystConfirmed:e.target.checked})}/><span>I manually confirmed these address components.</span></label><div className="modal-actions"><button className="button-secondary" disabled={resolverBusy} type="button" onClick={()=>setResolver(null)}>Cancel</button><button disabled={resolverBusy} type="submit">Save Address</button><button disabled={resolverBusy||!resolverForm.analystConfirmed} type="button" onClick={()=>saveResolution(true)}>Save &amp; Analyze</button></div></form></div></article></div>}
    {confirmation&&<div className="modal-backdrop confirmation-backdrop" role="dialog" aria-modal="true" aria-labelledby="confirmation-title"><article className="modal confirm-modal"><div className="confirm-icon" aria-hidden="true">!</div><div className="confirm-content"><p className="eyebrow">ACTION REQUIRES CONFIRMATION</p><h3 id="confirmation-title">{confirmation.title}</h3><p>{confirmation.message}</p><div className="modal-actions"><button className="button-secondary" onClick={()=>{confirmation.onCancel?.();setConfirmation(null);}}>Cancel</button><button onClick={acceptConfirmation}>{confirmation.confirmLabel}</button></div></div></article></div>}
  </section>;
}
